# Generated by Django 2.2.2 on 2019-07-11 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('users', '0002_auto_20190711_1955'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ourteam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurTeam',
            new_name='OurTeamPage',
        ),
        migrations.AlterModelOptions(
            name='ourteampage',
            options={'verbose_name': 'Our Team Page'},
        ),
        migrations.CreateModel(
            name='TeamMemberPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.UserProfile')),
            ],
            options={
                'verbose_name': 'Team Member Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
