# Generated by Django 2.2.2 on 2019-06-27 14:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='team',
            field=wagtail.core.fields.StreamField([('profiles', wagtail.core.blocks.StructBlock([('profiles', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.core.blocks.CharBlock(max_length=150, required=True)), ('position', wagtail.core.blocks.CharBlock(max_length=300, required=True)), ('department', wagtail.core.blocks.ChoiceBlock(choices=[('leadership', 'Leadership Team'), ('datascience', 'Data Science & Information Architecture'), ('analysis', 'Research & Analysis'), ('pm', 'Project Management'), ('hr_it_finance', 'HR, Facilities, IT & Finance'), ('partnerships', 'Strategic Partnerships'), ('coms', 'Communications'), ('policy', 'Policy & Engagement'), ('non_executive_directors', 'Non-Executive Directors'), ('board', 'Board Members'), ('consultants', 'Consultants'), ('fellow', 'Fellow')], icon='tag')), ('page_link', wagtail.core.blocks.PageChooserBlock(required=False)), ('active', wagtail.core.blocks.BooleanBlock(help_text=' Uncheck if team member no longer with DI', required=True))])))]))]),
        ),
    ]
