# Generated by Django 2.2.2 on 2019-07-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0002_teammemberpage_my_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteampage',
            name='hero_title',
        ),
    ]
