# Generated by Django 2.2.2 on 2019-06-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0002_auto_20190627_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='team',
        ),
    ]
