# Generated by Django 2.2.2 on 2019-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0002_auto_20190703_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='hero_image_credit_name',
            field=models.CharField(blank=True, help_text='Name of source of image used in hero if any', max_length=50, null=True, verbose_name='Image credit name'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='hero_image_credit_url',
            field=models.URLField(blank=True, help_text='A Link to the original source of the image if any', null=True, verbose_name='Image credit url'),
        ),
    ]
