# Generated by Django 2.2.2 on 2019-08-07 14:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
        ('ourteam', '0004_auto_20190802_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberpage',
            name='department',
        ),
        migrations.CreateModel(
            name='TeamMemberPageDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Department')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammember_departments', to='ourteam.TeamMemberPage')),
            ],
            options={
                'verbose_name': 'team member department',
                'verbose_name_plural': 'team member departments',
            },
        ),
    ]
