# Generated by Django 2.2.2 on 2019-10-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0006_auto_20191023_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteampage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='More about', max_length=255, verbose_name='Heading'),
        ),
    ]
