# Generated by Django 2.2.2 on 2019-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0007_ourteampage_other_pages_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberpage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='More about', max_length=255, verbose_name='Heading'),
        ),
    ]
