# Generated by Django 2.2.3 on 2019-08-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20190819_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Us Page'},
        ),
    ]
