# Generated by Django 2.2.3 on 2019-08-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_auto_20190828_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='organisation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='telephone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
