# Generated by Django 2.2.2 on 2019-10-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0011_auto_20191023_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='email_address',
        ),
    ]
