# Generated by Django 3.2.20 on 2023-08-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0024_alter_contactpage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='success_alert',
        ),
    ]
