# Generated by Django 2.2.3 on 2019-07-31 16:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0002_auto_20190723_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagerelatedlink',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogpagerelatedlink',
            name='related_link',
        ),
        migrations.AddField(
            model_name='blogpagerelatedlink',
            name='other_page',
            field=models.ForeignKey(blank=True, help_text='A page to link to in the "Other Pages or Related Links" section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='blogpagerelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_related_links', to='wagtailcore.Page'),
        ),
    ]
