# Generated by Django 2.2.3 on 2019-08-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190731_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticlepage',
            options={'verbose_name': 'Blog Article Page'},
        ),
    ]
