# Generated by Django 2.2.2 on 2019-09-05 15:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190902_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticlepage',
            name='external_author_name',
        ),
        migrations.RemoveField(
            model_name='blogarticlepage',
            name='external_author_page',
        ),
        migrations.RemoveField(
            model_name='blogarticlepage',
            name='external_author_photograph',
        ),
        migrations.RemoveField(
            model_name='blogarticlepage',
            name='external_author_title',
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='other_authors',
            field=wagtail.core.fields.StreamField([('internal_author', wagtail.core.blocks.PageChooserBlock(page_type=['ourteam.TeamMemberPage'], required=False)), ('external_author', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('photograph', wagtail.images.blocks.ImageChooserBlock(required=False)), ('page', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, help_text='Additional authors. Please fill in internal author page first.'),
        ),
    ]
