# Generated by Django 2.2.2 on 2019-11-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20191118_2113'),
        ('blog', '0025_auto_20191119_1138'),
    ]

    operations = [
    ]
