# Generated by Django 2.2.4 on 2020-05-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20200509_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlepage',
            name='colour',
            field=models.CharField(choices=[('poppy', 'Red'), ('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple'), ('leaf', 'Green')], default='poppy', max_length=256),
        ),
    ]
