# Generated by Django 2.2.4 on 2020-05-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200514_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticlepage',
            name='colour',
        ),
    ]
