# Generated by Django 3.0.7 on 2020-06-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200518_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagerelatedlink',
            options={'ordering': ['sort_order']},
        ),
    ]
