# Generated by Django 2.2.13 on 2020-07-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20200702_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlepage',
            name='call_to_action_body',
            field=models.TextField(blank=True, help_text='Optional: describe the purpose of your call to action in a bit more detail', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='call_to_action_button_text',
            field=models.CharField(blank=True, help_text='Optional: this is required to show the button', max_length=255, null=True, verbose_name='Button caption'),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='call_to_action_button_url',
            field=models.URLField(blank=True, help_text='Optional: this is required to show the button', max_length=255, null=True, verbose_name='Button URL'),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='call_to_action_title',
            field=models.CharField(blank=True, help_text='Optional: when left blank, the call to action will not be show', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
