# Generated by Django 2.2.13 on 2020-07-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200716_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticlepage',
            name='call_to_action_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='call_to_action_button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='call_to_action_title',
            field=models.CharField(blank=True, help_text='Leave title field blank to remove this call to action', max_length=255, null=True),
        ),
    ]
