version: "2.2"

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: di_website
      POSTGRES_USER: di_website
      POSTGRES_PASSWORD: di_website_pw
    restart: always
    volumes:
      - diwebsite_db:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "8900:9200"
      - "9700:9300"
    restart: always
    volumes:
      - index_db:/usr/share/elasticsearch/data
    logging:
        driver: "json-file"
        options:
            max-size: "1m"
            max-file: "10"

  web:
    depends_on:
      - db
      - rabbitmq
      - elasticsearch
    expose:
      - "8090"
    env_file: .env
    environment:
      - HS_API_KEY
      - HS_TICKET_PIPELINE
      - HS_TICKET_PIPELINE_STAGE
      - ELASTIC_SEARCH_URL
    build:
      context: .
    volumes:
      - ./:/code/
      - ./config/celery/default:/etc/default
      - ./config/celery/init.d:/etc/init.d
    restart: always
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
    restart: always

volumes:
  diwebsite_db:
    external: true
  index_db:
    driver: local
    external: true
