version: '3.4'

services:
    traefik:
        image: traefik
        networks:
            - webgateway
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.toml:/traefik.toml

networks:
    webgateway:
        driver: bridge
