# Generated by Django 2.2.2 on 2019-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationcountry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Publication countries'},
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='colour',
            field=models.CharField(choices=[('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='colour',
            field=models.CharField(choices=[('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='colour',
            field=models.CharField(choices=[('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='colour',
            field=models.CharField(choices=[('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='colour',
            field=models.CharField(choices=[('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='colour',
            field=models.CharField(choices=[('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
    ]
