# Generated by Django 2.2.2 on 2019-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacypublicationpage',
            name='colour',
            field=models.CharField(choices=[('', 'Red'), ('body--bluebell', 'Blue'), ('body--rose', 'Pink'), ('body--sunflower', 'Yellow'), ('body--marigold', 'Orange'), ('body--lavendar', 'Purple')], default='body--bluebell', max_length=256),
        ),
        migrations.AddField(
            model_name='publicationappendixpage',
            name='colour',
            field=models.CharField(choices=[('', 'Red'), ('body--bluebell', 'Blue'), ('body--rose', 'Pink'), ('body--sunflower', 'Yellow'), ('body--marigold', 'Orange'), ('body--lavendar', 'Purple')], default='body--bluebell', max_length=256),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='colour',
            field=models.CharField(choices=[('', 'Red'), ('body--bluebell', 'Blue'), ('body--rose', 'Pink'), ('body--sunflower', 'Yellow'), ('body--marigold', 'Orange'), ('body--lavendar', 'Purple')], default='body--bluebell', max_length=256),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='colour',
            field=models.CharField(choices=[('', 'Red'), ('body--bluebell', 'Blue'), ('body--rose', 'Pink'), ('body--sunflower', 'Yellow'), ('body--marigold', 'Orange'), ('body--lavendar', 'Purple')], default='body--bluebell', max_length=256),
        ),
        migrations.AddField(
            model_name='publicationsummarypage',
            name='colour',
            field=models.CharField(choices=[('', 'Red'), ('body--bluebell', 'Blue'), ('body--rose', 'Pink'), ('body--sunflower', 'Yellow'), ('body--marigold', 'Orange'), ('body--lavendar', 'Purple')], default='body--bluebell', max_length=256),
        ),
    ]
