# Generated by Django 2.2.2 on 2019-09-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20190916_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='colour',
            field=models.CharField(choices=[('poppy', 'Red'), ('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='colour',
            field=models.CharField(choices=[('poppy', 'Red'), ('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='colour',
            field=models.CharField(choices=[('poppy', 'Red'), ('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='colour',
            field=models.CharField(choices=[('poppy', 'Red'), ('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='colour',
            field=models.CharField(choices=[('poppy', 'Red'), ('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='colour',
            field=models.CharField(choices=[('poppy', 'Red'), ('bluebell', 'Blue'), ('rose', 'Pink'), ('sunflower', 'Yellow'), ('marigold', 'Orange'), ('lavendar', 'Purple')], default='bluebell', max_length=256),
        ),
    ]
