# Generated by Django 2.2.2 on 2019-09-17 19:04

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20190917_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortpublicationpage',
            name='authors',
            field=wagtail.fields.StreamField([('internal_author', wagtail.blocks.PageChooserBlock(page_type=['ourteam.TeamMemberPage'], required=False)), ('external_author', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=False)), ('photograph', wagtail.images.blocks.ImageChooserBlock(required=False)), ('page', wagtail.blocks.URLBlock(required=False))]))], blank=True),
        ),
    ]
