# Generated by Django 2.2.3 on 2019-09-19 15:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_shortpublicationpage_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legacypublicationpage',
            options={'verbose_name': 'Legacy Publication'},
        ),
        migrations.AlterModelOptions(
            name='publicationappendixpage',
            options={'verbose_name': 'Publication Appendix', 'verbose_name_plural': 'Publication Appendices'},
        ),
        migrations.AlterModelOptions(
            name='publicationchapterpage',
            options={'verbose_name': 'Publication Chapter'},
        ),
        migrations.AlterModelOptions(
            name='publicationsummarypage',
            options={'verbose_name': 'Publication Summary', 'verbose_name_plural': 'Publication Summaries'},
        ),
        migrations.AlterModelOptions(
            name='shortpublicationpage',
            options={'verbose_name': 'Short Publication'},
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('internal_author', wagtail.core.blocks.PageChooserBlock(icon='fa-user', page_type=['ourteam.TeamMemberPage'], required=False)), ('external_author', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('photograph', wagtail.images.blocks.ImageChooserBlock(required=False)), ('page', wagtail.core.blocks.URLBlock(required=False))], icon='fa-user'))], blank=True),
        ),
    ]
