# Generated by Django 2.2.2 on 2019-09-20 15:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('publications', '0005_shortpublicationpage_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legacypublicationpage',
            options={'verbose_name': 'Legacy Publication'},
        ),
        migrations.AlterModelOptions(
            name='publicationappendixpage',
            options={'verbose_name': 'Publication Appendix', 'verbose_name_plural': 'Publication Appendices'},
        ),
        migrations.AlterModelOptions(
            name='publicationchapterpage',
            options={'verbose_name': 'Publication Chapter'},
        ),
        migrations.AlterModelOptions(
            name='publicationsummarypage',
            options={'verbose_name': 'Publication Summary', 'verbose_name_plural': 'Publication Summaries'},
        ),
        migrations.AlterModelOptions(
            name='shortpublicationpage',
            options={'verbose_name': 'Short Publication'},
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='download_report_body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='report_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('internal_author', wagtail.core.blocks.PageChooserBlock(icon='fa-user', page_type=['ourteam.TeamMemberPage'], required=False)), ('external_author', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('photograph', wagtail.images.blocks.ImageChooserBlock(required=False)), ('page', wagtail.core.blocks.URLBlock(required=False))], icon='fa-user'))], blank=True),
        ),
    ]
