# Generated by Django 2.2.2 on 2019-09-24 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20190919_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortpublicationpage',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='This date will be used for display and ordering'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='This date will be used for display and ordering'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='This date will be used for display and ordering'),
        ),
    ]
