# Generated by Django 2.2.2 on 2019-09-24 14:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('publications', '0007_auto_20190924_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationCountry',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='PublicationRegion',
            new_name='Region',
        ),
        migrations.RemoveField(
            model_name='legacypublicationpage',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='publicationpage',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='shortpublicationpage',
            name='countries',
        ),
        migrations.CreateModel(
            name='PageCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publications.Country')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_countries', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
