# Generated by Django 2.2.2 on 2019-09-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20190924_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
