# Generated by Django 2.2.2 on 2019-09-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20190920_1511'),
        ('publications', '0009_auto_20190924_1452'),
    ]

    operations = [
    ]
