# Generated by Django 2.2.2 on 2019-09-30 16:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20190930_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Content for the legacy report', null=True),
        ),
    ]
