# Generated by Django 2.2.2 on 2019-09-30 17:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_publicationpagerelatedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacypublicationpage',
            name='footnotes_list',
            field=wagtail.fields.StreamField([('footnote', wagtail.blocks.StructBlock([('id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationappendixpage',
            name='footnotes_list',
            field=wagtail.fields.StreamField([('footnote', wagtail.blocks.StructBlock([('id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='footnotes_list',
            field=wagtail.fields.StreamField([('footnote', wagtail.blocks.StructBlock([('id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortpublicationpage',
            name='footnotes_list',
            field=wagtail.fields.StreamField([('footnote', wagtail.blocks.StructBlock([('id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
