# Generated by Django 2.2.2 on 2019-09-30 17:45

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20190930_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationsummarypage',
            name='footnotes_list',
            field=wagtail.fields.StreamField([('footnote', wagtail.blocks.StructBlock([('id', wagtail.blocks.IntegerBlock()), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
