# Generated by Django 2.2.2 on 2019-10-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('publications', '0017_auto_20190930_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationappendixpage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationappendixpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationappendixpage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='publicationappendixpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationappendixpage',
            name='report_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='report_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='publicationsummarypage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationsummarypage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationsummarypage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='publicationsummarypage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicationsummarypage',
            name='report_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
