# Generated by Django 2.2.3 on 2019-10-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0022_auto_20191023_0650'),
        ('publications', '0022_auto_20191017_1215'),
    ]

    operations = [
    ]
