# Generated by Django 2.2.4 on 2020-04-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0027_auto_20191118_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='publicationindexpage',
            options={'verbose_name': 'Resources Page'},
        ),
        migrations.AlterModelOptions(
            name='publicationtype',
            options={'ordering': ['name'], 'verbose_name': 'Resource Type'},
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='resource_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publications.ResourceCategory'),
        ),
    ]
