# Generated by Django 2.2.4 on 2020-04-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0028_auto_20200428_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'ordering': ['name'], 'verbose_name': 'Resource Categories'},
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='publication_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publications.PublicationType', verbose_name='Resource Type'),
        ),
    ]
