# Generated by Django 2.2.4 on 2020-04-29 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0030_auto_20200429_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='publication_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publications.PublicationType', verbose_name='Resource Type'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='publication_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publications.PublicationType', verbose_name='Resource Type'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='publication_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publications.PublicationType', verbose_name='Resource Type'),
        ),
    ]
