# Generated by Django 2.2.4 on 2020-04-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0031_auto_20200429_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationindexpage',
            options={'verbose_name': 'Resources Index Page'},
        ),
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'ordering': ['name'], 'verbose_name': 'Resource Category', 'verbose_name_plural': 'Resource Categories'},
        ),
    ]
