# Generated by Django 2.2.4 on 2020-04-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0032_auto_20200429_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualmedia',
            name='resource_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publications.PublicationType', verbose_name='Resource Type'),
        ),
    ]
