# Generated by Django 2.2.4 on 2020-04-29 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0033_audiovisualmedia_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualmedia',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='This date will be used for display and ordering'),
        ),
    ]
