# Generated by Django 2.2.4 on 2020-04-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0034_audiovisualmedia_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiovisualmedia',
            old_name='resource_type',
            new_name='publication_type',
        ),
    ]
