# Generated by Django 2.2.4 on 2020-04-30 06:40

from django.db import migrations
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0035_auto_20200429_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualmedia',
            name='full_width_video',
            field=wagtail.core.fields.StreamField([('external_author', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-video-camera', required=False, template='blocks/embed_block.html'))], blank=True),
        ),
    ]
