# Generated by Django 2.2.4 on 2020-05-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0037_auto_20200430_0854'),
        ('publications', '0032_auto_20200430_1654'),
    ]

    operations = [
    ]
