# Generated by Django 2.2.4 on 2020-05-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('publications', '0038_merge_20200503_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualmedia',
            name='featured_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
    ]
