# Generated by Django 2.2.4 on 2020-05-03 16:47

import di_website.publications.models
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0039_audiovisualmedia_featured_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiovisualmedia',
            name='featured_media',
        ),
        migrations.AddField(
            model_name='audiovisualmedia',
            name='media_content',
            field=wagtail.core.fields.StreamField([('media', di_website.publications.models.TestMediaBlock(icon='media'))], blank=True, null=True),
        ),
    ]
