# Generated by Django 2.2.4 on 2020-05-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0047_auto_20200513_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiovisualmedia',
            name='full_width_video',
        ),
        migrations.RemoveField(
            model_name='audiovisualmedia',
            name='media_content',
        ),
    ]
