# Generated by Django 3.0.7 on 2020-06-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0050_auto_20200608_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legacypublicationpagedataset',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='publicationappendixpagedataset',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='publicationchapterpagedataset',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='publicationpagedataset',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='publicationsummarypagedataset',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='shortpublicationpagedataset',
            options={'ordering': ['sort_order']},
        ),
    ]
