# Generated by Django 3.0.7 on 2020-06-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0052_audiovisualmedia_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiovisualmedia',
            name='other_pages_heading',
        ),
    ]
