# Generated by Django 2.2.13 on 2020-06-15 15:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('publications', '0052_audiovisualmedia_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVisualMediaTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_visual_media_topics', to='publications.AudioVisualMedia')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_audiovisualmediatopic_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
