# Generated by Django 2.2.13 on 2020-06-15 15:07

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('publications', '0053_audiovisualmediatopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualmedia',
            name='topics',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='publications.AudioVisualMediaTopic', to='taggit.Tag', verbose_name='Topics'),
        ),
    ]
