# Generated by Django 3.0.7 on 2020-06-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0054_audiovisualmedia_topics'),
        ('publications', '0053_remove_audiovisualmedia_other_pages_heading'),
    ]

    operations = [
    ]
