# Generated by Django 3.0.7 on 2020-06-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0054_auto_20200615_1123'),
        ('publications', '0055_merge_20200615_1550'),
    ]

    operations = [
    ]
