# Generated by Django 2.2.4 on 2020-06-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0056_publicationforewordpage_publicationforewordpagedatadownloads_publicationforewordpagedownloads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationforewordpage',
            options={'verbose_name': 'Publication foreword'},
        ),
    ]
