# Generated by Django 2.2.4 on 2020-06-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0058_auto_20200618_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationforewordpage',
            name='excerpt_field',
        ),
    ]
