# Generated by Django 2.2.13 on 2020-06-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0059_remove_publicationforewordpage_excerpt_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationforewordpage',
            options={'verbose_name': 'Publication Foreword'},
        ),
    ]
