# Generated by Django 3.0.7 on 2020-06-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0059_auto_20200622_0744'),
        ('publications', '0059_remove_publicationforewordpage_excerpt_field'),
    ]

    operations = [
    ]
