# Generated by Django 2.2.13 on 2020-07-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0061_auto_20200626_1419'),
        ('publications', '0063_auto_20200702_1244'),
    ]

    operations = [
    ]
