# Generated by Django 2.2.13 on 2020-07-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0062_auto_20200707_0518'),
        ('publications', '0063_auto_20200702_1244'),
    ]

    operations = [
    ]
