# Generated by Django 2.2.13 on 2020-07-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0064_merge_20200707_0553'),
        ('publications', '0065_auto_20200707_1733'),
    ]

    operations = [
    ]
