# Generated by Django 2.2.13 on 2020-07-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0065_auto_20200715_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='enable_for_all_chapters',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
