# Generated by Django 2.2.13 on 2020-07-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0068_auto_20200722_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationforewordpagedatadownloads',
            name='download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='downloads.DataDownload'),
        ),
    ]
