# Generated by Django 2.2.13 on 2020-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0068_auto_20200716_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortpublicationpage',
            name='call_to_action_body',
            field=models.TextField(blank=True, default='We shall email you a pdf version', null=True),
        ),
        migrations.AddField(
            model_name='shortpublicationpage',
            name='call_to_action_button_text',
            field=models.CharField(blank=True, default='Signup to receive a copy in your inbox', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shortpublicationpage',
            name='call_to_action_button_url',
            field=models.URLField(blank=True, default='https://us11.list-manage.com/subscribe?u=a829237ca0cf1470615c7f059&id=ce30e2af0f', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shortpublicationpage',
            name='call_to_action_title',
            field=models.CharField(blank=True, default='Receive a pdf version', help_text='Leave title field blank to remove this call to action', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='call_to_action_title',
            field=models.CharField(blank=True, default='Receive a pdf version', help_text='Leave title field blank to remove this call to action', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='call_to_action_title',
            field=models.CharField(blank=True, default='Receive a pdf version', help_text='Leave title field blank to remove this call to action', max_length=255, null=True),
        ),
    ]
