# Generated by Django 2.2.13 on 2020-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0069_auto_20200728_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True, verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True, verbose_name='Section title'),
        ),
    ]
