# Generated by Django 2.2.13 on 2020-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0070_auto_20200716_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='call_to_action_button_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='call_to_action_button_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='call_to_action_button_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
