# Generated by Django 2.2.13 on 2020-07-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0066_merge_20200716_0848'),
        ('publications', '0071_auto_20200716_1108'),
    ]

    operations = [
    ]
