# Generated by Django 2.2.13 on 2020-07-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('publications', '0071_auto_20200730_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationforewordpage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True, verbose_name='Section body'),
        ),
        migrations.AddField(
            model_name='publicationforewordpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True, verbose_name='Button caption'),
        ),
        migrations.AddField(
            model_name='publicationforewordpage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Report cover'),
        ),
        migrations.AddField(
            model_name='publicationforewordpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True, verbose_name='Section title'),
        ),
        migrations.AddField(
            model_name='publicationforewordpage',
            name='report_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True, verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Report cover'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True, verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Report cover'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True, verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Report cover'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True, verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Report cover'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='download_report_body',
            field=models.TextField(blank=True, null=True, verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, null=True, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='download_report_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Report cover'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, null=True, verbose_name='Section title'),
        ),
    ]
