# Generated by Django 2.2.16 on 2021-02-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0074_auto_20200924_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationtype',
            name='show_in_filter',
            field=models.BooleanField(default=True, help_text='Used to exclude obsolete tags that are still tied to resources', verbose_name='Show in filter'),
        ),
    ]
