# Generated by Django 3.1 on 2020-10-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0074_auto_20200924_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='hide_date',
            field=models.BooleanField(default=True),
        ),
    ]
