# Generated by Django 3.1 on 2020-10-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0075_publicationpage_hide_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should the published date appear under related content items ?', verbose_name='Hide Related Content Date'),
        ),
    ]
