# Generated by Django 3.1 on 2020-10-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0077_auto_20201021_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='hide_date',
            field=models.BooleanField(default=False, help_text='Should the published date appear on related links items ?', verbose_name='Related Links Date'),
        ),
    ]
