# Generated by Django 3.1 on 2020-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0079_auto_20201021_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationforewordpage',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should the date appear on related links items ?', verbose_name='Hide Related Links Date'),
        ),
    ]
