# Generated by Django 2.2.16 on 2021-06-17 15:41

from django.db import migrations


def move_calls_to_action(apps, schema_editor):
    PublicationPage = apps.get_model('publications', 'PublicationPage')
    PublicationCTA = apps.get_model('publications', 'PublicationCallToAction')

    for page in PublicationPage.objects.all():
        if page.call_to_action_title and page.publication_cta.count() < 2:
            cta = PublicationCTA(
                title=page.call_to_action_title,
                body=page.call_to_action_body,
                button_text=page.call_to_action_button_text,
                button_url=page.call_to_action_button_url,)
            page.publication_cta.add(cta)
            cta.save()
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0080_publicationcalltoaction'),
    ]

    operations = [
        migrations.RunPython(move_calls_to_action),
    ]
