# Generated by Django 3.1 on 2020-10-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0080_publicationforewordpage_hide_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovisualmedia',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should we hide the date on related links items ?', verbose_name='Hide Related Links Date'),
        ),
        migrations.AddField(
            model_name='legacypublicationpage',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should we hide the date on related links items ?', verbose_name='Hide Related Links Date'),
        ),
        migrations.AddField(
            model_name='publicationappendixpage',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should we hide the date on related links items ?', verbose_name='Hide Related Links Date'),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should we hide the date on related links items ?', verbose_name='Hide Related Links Date'),
        ),
        migrations.AddField(
            model_name='shortpublicationpage',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should we hide the date on related links items ?', verbose_name='Hide Related Links Date'),
        ),
        migrations.AlterField(
            model_name='publicationforewordpage',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should we hide the date on related links items ?', verbose_name='Hide Related Links Date'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='hide_date',
            field=models.BooleanField(default=True, help_text='Should we hide the date on related links items ?', verbose_name='Hide Related Links Date'),
        ),
    ]
