# Generated by Django 2.2.16 on 2021-06-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0081_auto_20210617_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpage',
            name='call_to_action_body',
        ),
        migrations.RemoveField(
            model_name='publicationpage',
            name='call_to_action_button_text',
        ),
        migrations.RemoveField(
            model_name='publicationpage',
            name='call_to_action_button_url',
        ),
        migrations.RemoveField(
            model_name='publicationpage',
            name='call_to_action_title',
        ),
    ]
