# Generated by Django 2.2.16 on 2021-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0083_publicationcalltoaction_inherit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcalltoaction',
            name='inherit',
            field=models.BooleanField(default=False, help_text='Optional: show this CTA on child pages'),
        ),
    ]
