# Generated by Django 2.2.16 on 2021-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0084_auto_20210618_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcalltoaction',
            name='data_format',
            field=models.TextField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('top-bottom', 'Top & Bottom')], default='plain', help_text='Options are plain, currency, percent', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationcalltoaction',
            name='position',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom'), ('top-bottom', 'Top & Bottom')], default='top', max_length=100, null=True, verbose_name='Position'),
        ),
    ]
