# Generated by Django 2.2.16 on 2021-06-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0085_auto_20210618_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationcalltoaction',
            name='data_format',
        ),
        migrations.AlterField(
            model_name='publicationcalltoaction',
            name='inherit',
            field=models.BooleanField(default=True, help_text='Optional: show this CTA on child pages'),
        ),
    ]
