# Generated by Django 2.2.20 on 2021-07-06 09:25

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0086_auto_20210621_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationappendixpage',
            name='add_content_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))], icon='fa-link'))], blank=True),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='add_content_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))], icon='fa-link'))], blank=True),
        ),
        migrations.AddField(
            model_name='publicationforewordpage',
            name='add_content_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))], icon='fa-link'))], blank=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='read_online_button_text',
            field=models.CharField(blank=True, default='Read Online', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='request_hard_copy_text',
            field=models.CharField(blank=True, default='Request a hard copy', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='use_other_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationsummarypage',
            name='add_content_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))], icon='fa-link'))], blank=True),
        ),
    ]
