# Generated by Django 2.2.16 on 2021-06-21 13:24

from django.db import migrations

def default_inherit(apps, schema_editor):
    PublicationCTA = apps.get_model('publications', 'PublicationCallToAction')

    for cta in PublicationCTA.objects.all():
        cta.inherit = True
        cta.save()

class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0086_auto_20210621_0931'),
    ]

    operations = [
        migrations.RunPython(default_inherit),
    ]
