# Generated by Django 2.2.16 on 2021-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0087_auto_20210621_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='read_online_button_text',
            field=models.CharField(blank=True, default='Read Online', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='request_hard_copy_text',
            field=models.CharField(blank=True, default='Request a hard copy', max_length=256, null=True),
        ),
    ]
