# Generated by Django 2.2.20 on 2021-07-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0087_auto_20210706_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationpage',
            old_name='read_online_button_text',
            new_name='read_online_text',
        ),
        migrations.RemoveField(
            model_name='publicationappendixpage',
            name='add_content_links',
        ),
        migrations.RemoveField(
            model_name='publicationchapterpage',
            name='add_content_links',
        ),
        migrations.RemoveField(
            model_name='publicationforewordpage',
            name='add_content_links',
        ),
        migrations.RemoveField(
            model_name='publicationpage',
            name='use_other_template',
        ),
        migrations.RemoveField(
            model_name='publicationsummarypage',
            name='add_content_links',
        ),
    ]
