# Generated by Django 2.2.20 on 2021-07-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0088_auto_20210707_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationpage',
            old_name='read_online_text',
            new_name='read_online_button_text',
        ),
    ]
