# Generated by Django 3.2.7 on 2021-10-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0090_auto_20210708_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='read_online_button_text',
            field=models.CharField(blank=True, default='Read Online', max_length=256, null=True, verbose_name='Read Online'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='request_hard_copy_text',
            field=models.CharField(blank=True, default='Request a hard copy', max_length=256, null=True, verbose_name='Read Hard Copy'),
        ),
    ]
