# Generated by Django 3.2.7 on 2022-01-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0093_auto_20220119_0540'),
        ('publications', '0093_shortpublicationpage_use_state'),
    ]

    operations = [
    ]
