# Generated by Django 3.2.7 on 2022-01-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0093_shortpublicationpage_use_state'),
        ('publications', '0095_auto_20220114_0957'),
    ]

    operations = [
    ]
