# Generated by Django 3.2.7 on 2022-01-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0094_merge_20220119_0631'),
        ('publications', '0096_merge_20220119_0514'),
    ]

    operations = [
    ]
