# Generated by Django 3.2.7 on 2022-01-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0097_auto_20220119_1804'),
        ('publications', '0097_merge_20220119_1121'),
    ]

    operations = [
    ]
