# Generated by Django 3.2.12 on 2022-02-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0100_auto_20220125_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortpublicationpage',
            name='use_state',
        ),
    ]
