# Generated by Django 3.2.13 on 2022-07-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0101_remove_shortpublicationpage_use_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='related_options',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253),
        ),
    ]
