# Generated by Django 3.2.13 on 2022-08-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0102_alter_audiovisualmedia_sections'),
        ('publications', '0103_auto_20220720_0956'),
    ]

    operations = [
    ]
