# Generated by Django 3.2.13 on 2022-08-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0104_merge_20220803_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiovisualmedia',
            name='related_options',
        ),
        migrations.RemoveField(
            model_name='legacypublicationpage',
            name='related_options',
        ),
        migrations.RemoveField(
            model_name='publicationappendixpage',
            name='related_options',
        ),
        migrations.RemoveField(
            model_name='publicationchapterpage',
            name='related_options',
        ),
        migrations.RemoveField(
            model_name='publicationforewordpage',
            name='related_options',
        ),
        migrations.RemoveField(
            model_name='publicationpage',
            name='related_options',
        ),
        migrations.RemoveField(
            model_name='publicationsummarypage',
            name='related_options',
        ),
        migrations.RemoveField(
            model_name='shortpublicationpage',
            name='related_options',
        ),
        migrations.AddField(
            model_name='audiovisualmedia',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AddField(
            model_name='legacypublicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AddField(
            model_name='publicationappendixpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AddField(
            model_name='publicationchapterpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AddField(
            model_name='publicationforewordpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AddField(
            model_name='publicationsummarypage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AddField(
            model_name='shortpublicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
    ]
