# Generated by Django 3.2.12 on 2022-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0105_auto_20220803_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovisualmedia',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='MANUAL', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='MANUAL', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='MANUAL', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='MANUAL', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationforewordpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='MANUAL', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='MANUAL', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='MANUAL', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COUNTRY', 'Country'), ('TOPIC', 'Topic')], default='MANUAL', max_length=253, verbose_name='Show By'),
        ),
    ]
