# Generated by Django 3.2.15 on 2022-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0106_auto_20220920_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovisualmedia',
            name='related_option_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Country', 'Country'), ('Topic', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Country', 'Country'), ('Topic', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='related_option_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Country', 'Country'), ('Topic', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='related_option_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Country', 'Country'), ('Topic', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationforewordpage',
            name='related_option_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Country', 'Country'), ('Topic', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Country', 'Country'), ('Topic', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='related_option_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Country', 'Country'), ('Topic', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='related_option_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Country', 'Country'), ('Topic', 'Topic')], default='Manual', max_length=253, verbose_name='Show By'),
        ),
    ]
