# Generated by Django 3.2.15 on 2022-09-28 01:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0109_auto_20220923_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('podcast_provider_platform', models.CharField(choices=[('apple', 'Apple'), ('spotify', 'Spotify'), ('google', 'Google'), ('amazon', 'Amazon')], max_length=100)),
                ('link_url', models.CharField(max_length=255)),
                ('podcast', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_providers', to='publications.audiovisualmedia')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
