# Generated by Django 3.2.15 on 2022-09-28 01:31

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0110_podcastprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastprovider',
            name='podcast',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcast_providers', to='publications.audiovisualmedia'),
        ),
    ]
