# Generated by Django 3.2.15 on 2022-09-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0112_auto_20220928_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastprovider',
            options={'verbose_name': 'Podcast Provider', 'verbose_name_plural': 'Podcast Providers'},
        ),
        migrations.RemoveField(
            model_name='podcastprovider',
            name='sort_order',
        ),
    ]
