# Generated by Django 3.2.16 on 2022-10-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0117_auto_20221012_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='download_button_caption',
            field=models.CharField(blank=True, default='Downloads', max_length=100, null=True, verbose_name='Downloads'),
        ),
    ]
