# Generated by Django 3.2.15 on 2023-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0119_auto_20221205_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovisualmedia',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True),
        ),
        migrations.AlterField(
            model_name='publicationforewordpage',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='This date will be used for display and ordering', null=True),
        ),
    ]
