# Generated by Django 3.2.15 on 2023-03-28 17:05

from django.db import migrations
from di_website.publications.models import (
    PublicationAppendixPage,
    PublicationChapterPage,
    PublicationSummaryPage,
    PublicationForewordPage,
    ShortPublicationPage,
    AudioVisualMedia
)

def update_published_date(apps, schema_editor):
    # I could not use apps - not sure why but the objects it produces don't have the Wagtail properties & methods
    publication_classes = [
        PublicationAppendixPage,
        PublicationChapterPage,
        PublicationSummaryPage,
        PublicationForewordPage,
        ShortPublicationPage,
        AudioVisualMedia
    ]

    for PublicationClass in publication_classes:
        for item in PublicationClass.objects.all():
            parent = item.get_parent().specific
            if hasattr(parent, 'published_date') and parent.published_date:
                item.published_date = parent.published_date
                item.save()


def revert_not_really(apps, schema_editor):
    print('Cannot be reverted! Sorry!!')




class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0120_auto_20230328_1635'),
    ]

    operations = [
        migrations.RunPython(update_published_date, revert_not_really)
    ]
