# Generated by Django 3.2.16 on 2023-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0124_auto_20230519_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='download_report_body',
            field=models.TextField(blank=True, default='', verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='legacypublicationpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='download_report_body',
            field=models.TextField(blank=True, default='', verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationappendixpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='download_report_body',
            field=models.TextField(blank=True, default='', verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationchapterpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='publicationforewordpage',
            name='download_report_body',
            field=models.TextField(blank=True, default='', verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationforewordpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationforewordpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='download_button_caption',
            field=models.CharField(blank=True, default='Downloads', max_length=100, verbose_name='Downloads'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='download_report_body',
            field=models.TextField(blank=True, default='', verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='read_online_button_text',
            field=models.CharField(blank=True, default='Read Online', max_length=256, verbose_name='Read Online'),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='request_hard_copy_text',
            field=models.CharField(blank=True, default='Request a hard copy', max_length=256, verbose_name='Read Hard Copy'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='download_report_body',
            field=models.TextField(blank=True, default='', verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='publicationsummarypage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='download_report_body',
            field=models.TextField(blank=True, default='', verbose_name='Section body'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='download_report_button_text',
            field=models.CharField(blank=True, default='Download now', max_length=255, verbose_name='Button caption'),
        ),
        migrations.AlterField(
            model_name='shortpublicationpage',
            name='download_report_title',
            field=models.CharField(blank=True, default='Download this report', max_length=255, verbose_name='Section title'),
        ),
    ]
