# Generated by Django 3.2.19 on 2023-06-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0125_alter_publicationforewordpage_content'),
        ('publications', '0125_auto_20230526_1446'),
    ]

    operations = [
    ]
