# Generated by Django 3.2.16 on 2023-05-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0125_alter_publicationforewordpage_content'),
        ('publications', '0125_auto_20230526_1446'),
    ]

    operations = [
    ]
