# Generated by Django 2.2.4 on 2019-08-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpage',
            name='contactus_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Contact Us URL'),
        ),
        migrations.AddField(
            model_name='errorpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Error Reporting Email'),
        ),
        migrations.AddField(
            model_name='errorpage',
            name='home_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Home Page URL'),
        ),
    ]
