# Generated by Django 2.2.6 on 2020-01-15 11:03

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.search.index
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='spotlightpage',
            name='themes',
            field=wagtail.fields.StreamField([('theme', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=True)), ('indicators', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('ddw_id', wagtail.blocks.CharBlock(max_length=255, required=True, verbose_name='DDW ID')), ('name', wagtail.blocks.TextBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(help_text='A description of this indicator')), ('source', wagtail.snippets.blocks.SnippetChooserBlock('spotlight.Source')), ('color', wagtail.snippets.blocks.SnippetChooserBlock('spotlight.Colour')), ('start_year', wagtail.blocks.IntegerBlock()), ('end_year', wagtail.blocks.IntegerBlock()), ('range', wagtail.blocks.CharBlock(max_length=100, required=False)), ('value_prefix', wagtail.blocks.CharBlock(max_length=100, required=False)), ('value_suffix', wagtail.blocks.CharBlock(max_length=100, required=False)), ('tooltip_template', wagtail.blocks.TextBlock(help_text='Text for the tooltip.Template strings can be used to substitute values e.g. {name}', required=True))])))]))]),
        ),
    ]
