# Generated by Django 2.2.6 on 2020-01-15 11:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0003_auto_20200115_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colour',
            new_name='SpotlightColour',
        ),
        migrations.RenameModel(
            old_name='Source',
            new_name='SpotlightSource',
        ),
        migrations.AlterField(
            model_name='spotlightpage',
            name='themes',
            field=wagtail.fields.StreamField([('theme', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock(required=True)), ('indicators', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('ddw_id', wagtail.blocks.CharBlock(label='DDW ID', max_length=255, required=True)), ('name', wagtail.blocks.TextBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(help_text='A description of this indicator')), ('source', wagtail.snippets.blocks.SnippetChooserBlock('spotlight.SpotlightSource')), ('color', wagtail.snippets.blocks.SnippetChooserBlock('spotlight.SpotlightColour')), ('start_year', wagtail.blocks.IntegerBlock()), ('end_year', wagtail.blocks.IntegerBlock()), ('range', wagtail.blocks.CharBlock(max_length=100, required=False)), ('value_prefix', wagtail.blocks.CharBlock(max_length=100, required=False)), ('value_suffix', wagtail.blocks.CharBlock(max_length=100, required=False)), ('tooltip_template', wagtail.blocks.TextBlock(help_text='Text for the tooltip.Template strings can be used to substitute values e.g. {name}', required=True))])))]))]),
        ),
    ]
