# Generated by Django 2.2.6 on 2020-01-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0004_auto_20200115_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotlightcolour',
            options={'verbose_name': 'Spotlight Colour', 'verbose_name_plural': 'Spotlight Colours'},
        ),
        migrations.AlterModelOptions(
            name='spotlightsource',
            options={'verbose_name': 'Spotlight Source', 'verbose_name_plural': 'Spotlight Sources'},
        ),
    ]
