# Generated by Django 2.2.6 on 2020-01-16 16:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0006_auto_20200116_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Spotlight',
                'verbose_name_plural': 'Spotlights',
            },
        ),
        migrations.CreateModel(
            name='SpotlightTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spotlight', models.ForeignKey(blank=True, help_text='The spotlight this theme belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spotlight.Spotlight')),
            ],
            options={
                'verbose_name': 'Spotlight Theme',
                'verbose_name_plural': 'Spotlight Themes',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SpotlightIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddw_id', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, help_text='A description of this indicator', null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('range', models.CharField(blank=True, help_text='The range of values shown on the legend', max_length=100, null=True)),
                ('value_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('value_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('tooltip_template', models.TextField(help_text='Text for the tooltip.Template strings can be used to substitute values e.g. {name}')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spotlight.SpotlightColour')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spotlight.SpotlightSource')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spotlight.SpotlightTheme')),
            ],
            options={
                'verbose_name': 'Spotlight Indicator',
                'verbose_name_plural': 'Spotlight Indicators',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
