# Generated by Django 2.2.6 on 2020-01-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0007_spotlight_spotlightindicator_spotlighttheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlightpage',
            name='themes',
        ),
        migrations.AddField(
            model_name='spotlightpage',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spotlight.Spotlight'),
        ),
    ]
