# Generated by Django 2.2.6 on 2020-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0008_auto_20200116_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlight',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
