# Generated by Django 2.2.6 on 2020-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0009_spotlight_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlighttheme',
            name='slug',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='slug',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
