# Generated by Django 2.2.6 on 2020-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0010_auto_20200117_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
