# Generated by Django 2.2.6 on 2020-01-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0011_auto_20200117_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spotlighttheme',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
