# Generated by Django 2.2.6 on 2020-01-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0012_auto_20200117_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlightindicator',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotlightindicator',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotlightindicator',
            name='tooltip_template',
            field=models.TextField(blank=True, help_text='Text for the tooltip.Template strings can be used to substitute values e.g. {name}', null=True),
        ),
    ]
