# Generated by Django 2.2.6 on 2020-02-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0014_spotlightpage_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightindicator',
            name='content_template',
            field=models.TextField(blank=True, help_text='Template strings can be used to substitute values e.g. {name} | {value} is the value template string', null=True),
        ),
        migrations.AddField(
            model_name='spotlighttheme',
            name='section',
            field=models.CharField(blank=True, help_text='Determins which section on the spotlights a particular theme and its indicators appears', max_length=200, null=True),
        ),
    ]
