# Generated by Django 2.2.6 on 2020-02-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0016_auto_20200219_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlightindicator',
            name='content_template',
            field=models.TextField(blank=True, default='{value_prefix}{value}{value_suffix}', help_text='Template strings can be used to substitute values e.g. {name} | {value} is the value template string', null=True),
        ),
    ]
