# Generated by Django 2.2.6 on 2020-02-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0017_auto_20200219_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightpage',
            name='currency_code',
            field=models.CharField(default='', help_text='UGX, KES', max_length=100),
        ),
    ]
