# Generated by Django 2.2.6 on 2020-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0018_spotlightpage_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightindicator',
            name='data_format',
            field=models.TextField(choices=[('percent', 'Percentage'), ('plain', 'Plain'), ('currency', 'Currency')], default='plain', max_length=100),
        ),
    ]
