# Generated by Django 2.2.6 on 2020-02-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0020_auto_20200224_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotlightIndicator',
        ),
    ]
