# Generated by Django 2.2.6 on 2020-02-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('spotlight', '0021_delete_spotlightindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightTheme',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=200)),
                ('section', models.CharField(blank=True, help_text='Determines which section on the spotlights a particular theme and its indicators appears e.g map,facts', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Spotlight Theme',
            },
            bases=('wagtailcore.page',),
        ),
    ]
