# Generated by Django 2.2.6 on 2020-02-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('spotlight', '0022_spotlighttheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightIndicator',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('ddw_id', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, help_text='A description of this indicator', null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('data_format', models.TextField(choices=[('percent', 'Percentage'), ('plain', 'Plain'), ('currency', 'Currency')], default='plain', max_length=100)),
                ('range', models.CharField(blank=True, help_text='The range of values shown on the legend', max_length=100, null=True)),
                ('value_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('value_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('tooltip_template', models.TextField(blank=True, help_text='Text for the tooltip.Template strings can be used to substitute values e.g. {name}', null=True)),
                ('content_template', models.TextField(blank=True, default='[]', help_text='Template strings can be used to substitute values e.g. {name} | {value} is the value template string', null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spotlight.SpotlightColour')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='spotlight.SpotlightSource')),
            ],
            options={
                'verbose_name': 'Spotlight Indicator',
            },
            bases=('wagtailcore.page',),
        ),
    ]
