# Generated by Django 2.2.6 on 2020-02-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0023_spotlightindicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlightindicator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='spotlightpage',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='spotlighttheme',
            name='name',
        ),
    ]
