# Generated by Django 2.2.6 on 2020-02-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0024_auto_20200224_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spotlight',
        ),
    ]
