# Generated by Django 2.2.6 on 2020-02-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0025_delete_spotlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlightindicator',
            name='content_template',
            field=models.TextField(blank=True, default='', help_text='Template strings can be used to substitute values e.g. {name} | {value} is the value template string', null=True),
        ),
    ]
