# Generated by Django 2.2.6 on 2020-02-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0027_auto_20200226_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightpage',
            name='country_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
