# Generated by Django 2.2.12 on 2020-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0030_auto_20200401_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightindicator',
            name='excluded_years',
            field=models.TextField(blank=True, help_text='Comma separated values e.g. 2002,2004,2017', null=True),
        ),
    ]
