# Generated by Django 2.2.6 on 2020-04-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0031_spotlightindicator_excluded_years'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotlightSource',
        ),
        migrations.AlterField(
            model_name='spotlightindicator',
            name='source',
            field=models.TextField(blank=True, help_text='Where is the data from?', null=True),
        ),
    ]
