# Generated by Django 2.2.4 on 2020-04-15 03:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0034_auto_20200415_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryspotlight',
            name='country_spotlight',
            field=wagtail.core.fields.StreamField([('country_information', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.CharBlock(required=False)), ('spotlight_page', wagtail.core.blocks.PageChooserBlock(page_type=['spotlight.SpotlightPage'], required=False))]))], blank=True, help_text='Add Country Spotlight.'),
        ),
    ]
