# Generated by Django 2.2.4 on 2020-04-15 07:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0037_auto_20200415_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Optional: a brief description about this page', verbose_name='Description'),
        ),
    ]
