# Generated by Django 2.2.4 on 2020-04-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0038_spotlightpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlightpage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: a brief description about this page', verbose_name='Description'),
        ),
    ]
