# Generated by Django 2.2.4 on 2020-04-15 23:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0039_auto_20200415_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryspotlight',
            name='country_spotlight',
            field=wagtail.core.fields.StreamField([('country_information', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'anchor'], icon='fa-paragraph', template='blocks/paragraph_block.html')), ('spotlight_page', wagtail.core.blocks.StreamBlock([('add_spotlight_page', wagtail.core.blocks.PageChooserBlock(page_type=['spotlight.SpotlightPage'], required=False))], blank=True, help_text='Add Page')), ('background', wagtail.core.blocks.ChoiceBlock(choices=[('light', 'Light'), ('dark', 'Dark')], help_text='Select background theme for this section'))]))], blank=True, help_text='Add Country Spotlight.'),
        ),
    ]
