# Generated by Django 2.2.4 on 2020-04-16 15:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0052_auto_20200416_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlightlocationcomparisonpage',
            name='default_locations',
            field=wagtail.fields.StreamField([('locations', wagtail.blocks.StructBlock([('name', wagtail.blocks.TextBlock()), ('geocode', wagtail.blocks.TextBlock())]))], blank=True, null=True, verbose_name='Default Locations'),
        ),
    ]
