# Generated by Django 2.2.4 on 2020-04-17 06:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0053_auto_20200416_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryspotlight',
            name='country_spotlight',
            field=wagtail.core.fields.StreamField([('country_info', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('spotlight_description', wagtail.core.blocks.StreamBlock([('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'anchor'], icon='fa-paragraph', template='blocks/paragraph_block.html'))], blank=True, max_num=2)), ('spotlight_page', wagtail.core.blocks.StreamBlock([('add_spotlight_page', wagtail.core.blocks.PageChooserBlock(page_type=['spotlight.SpotlightPage'], required=False)), ('add_location_comparison_page', wagtail.core.blocks.PageChooserBlock(page_type=['spotlight.SpotlightLocationComparisonPage'], required=False))], blank=True, block_counts={'add_location_comparison_page': {'max_num': 1}, 'add_spotlight_page': {'max_num': 1}}, max_num=2)), ('background_theme', wagtail.core.blocks.ChoiceBlock(choices=[('light', 'Light'), ('dark', 'Dark')], help_text='Select background theme for this section'))]))], blank=True, help_text='Add Country Spotlight.'),
        ),
    ]
