# Generated by Django 2.2.4 on 2020-04-18 11:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0054_auto_20200417_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryspotlight',
            name='country_spotlight',
            field=wagtail.core.fields.StreamField([('country_info', wagtail.core.blocks.StructBlock([('spotlight_page', wagtail.core.blocks.StreamBlock([('add_spotlight_page', wagtail.core.blocks.PageChooserBlock(page_type=['spotlight.SpotlightPage'], required=False))], blank=True, block_counts={'add_spotlight_page': {'max_num': 2}}, max_num=2)), ('background_theme', wagtail.core.blocks.ChoiceBlock(choices=[('light', 'Light'), ('dark', 'Dark')], help_text='Select background theme for this section'))]))], blank=True, help_text='Add Country Spotlight.'),
        ),
    ]
