# Generated by Django 2.2.4 on 2020-04-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0055_auto_20200418_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryspotlight',
            name='country_spotlight',
        ),
    ]
