# Generated by Django 2.2.4 on 2020-04-18 11:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0056_remove_countryspotlight_country_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryspotlight',
            name='country_spotlight',
            field=wagtail.core.fields.StreamField([('country_info', wagtail.core.blocks.StreamBlock([('add_spotlight_page', wagtail.core.blocks.PageChooserBlock(page_type=['spotlight.SpotlightPage'], required=False))], blank=True, block_counts={'add_spotlight_page': {'max_num': 2}}, max_num=2))], blank=True, help_text='Add Country Spotlight.'),
        ),
    ]
