# Generated by Django 2.2.4 on 2020-04-18 11:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0057_countryspotlight_country_spotlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryspotlight',
            name='country_spotlight',
            field=wagtail.fields.StreamField([('add_spotlight_page', wagtail.blocks.PageChooserBlock(page_type=['spotlight.SpotlightPage'], required=False))], blank=True, help_text='Add Country Spotlight.'),
        ),
    ]
