# Generated by Django 2.2.6 on 2020-04-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0032_auto_20200415_1653'),
        ('spotlight', '0058_auto_20200418_1154'),
    ]

    operations = [
    ]
