# Generated by Django 2.2.6 on 2020-04-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0059_merge_20200420_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryspotlight',
            name='country_spotlight',
        ),
        migrations.RemoveField(
            model_name='spotlightlocationcomparisonpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='spotlightlocationcomparisonpage',
            name='hero_image_credit_name',
        ),
        migrations.RemoveField(
            model_name='spotlightlocationcomparisonpage',
            name='hero_image_credit_url',
        ),
        migrations.RemoveField(
            model_name='spotlightlocationcomparisonpage',
            name='hero_link',
        ),
        migrations.RemoveField(
            model_name='spotlightlocationcomparisonpage',
            name='hero_link_caption',
        ),
        migrations.RemoveField(
            model_name='spotlightlocationcomparisonpage',
            name='hero_text',
        ),
        migrations.RemoveField(
            model_name='spotlightlocationcomparisonpage',
            name='search_image',
        ),
    ]
