# Generated by Django 2.2.3 on 2019-10-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20191023_0650'),
        ('general', '0015_auto_20191023_0700'),
    ]

    operations = [
    ]
