# Generated by Django 2.2.3 on 2019-10-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_auto_20191023_1012'),
        ('general', '0017_auto_20191025_1146'),
    ]

    operations = [
    ]
