# Generated by Django 2.2.6 on 2019-10-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_auto_20191028_1330'),
        ('general', '0020_auto_20191025_1305'),
    ]

    operations = [
    ]
