# Generated by Django 2.2.3 on 2019-08-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectpagerelatedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpagerelatedlink',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
