# Generated by Django 2.2.3 on 2019-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectpagerelatedlink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpagerelatedlink',
            name='title',
            field=models.CharField(blank=True, help_text='Specify a title for this section', max_length=255, null=True, verbose_name='Related Content Title'),
        ),
    ]
