# Generated by Django 2.2.3 on 2019-08-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190806_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpagerelatedlink',
            name='title',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='other_pages_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Title'),
        ),
    ]
