# Generated by Django 2.2.4 on 2019-08-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('project', '0007_auto_20190814_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpagerelatedlink',
            name='extra_page',
            field=models.ForeignKey(blank=True, help_text='An extra page to link to projects in Focus Area Section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Page'),
        ),
    ]
