# Generated by Django 2.2.4 on 2019-08-14 11:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20190814_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusareaspagelink',
            name='focus_area_text',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.RichTextBlock(classname='full title')), ('sub_title', wagtail.blocks.RichTextBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))], blank=True, null=True),
        ),
    ]
