# Generated by Django 2.2.4 on 2019-08-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_focusareaspagerelatedlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusareaspage',
            options={'verbose_name': 'Focus Areas Page'},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Project Page'},
        ),
    ]
