# Generated by Django 2.2.4 on 2019-08-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20190820_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusareaspagelink',
            old_name='focus_area_sub_paragraph',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='focusareaspagelink',
            old_name='focus_area_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='focusareaspagelink',
            old_name='focus_area_sub_title',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='focusareaspagelink',
            old_name='focus_area_title',
            new_name='title',
        ),
    ]
