# Generated by Django 2.2.4 on 2019-08-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20190820_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusareaspagelink',
            old_name='sub_title',
            new_name='subtitle',
        ),
    ]
