# Generated by Django 2.2.4 on 2019-08-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20190820_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusareaspagelink',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Focus Area Image'),
        ),
    ]
