# Generated by Django 2.2.4 on 2019-08-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20190820_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusareaspagelink',
            name='image',
            field=models.ForeignKey(help_text='Add an image to this focus area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image', verbose_name='Focus Area Image'),
        ),
    ]
