# Generated by Django 2.2.4 on 2019-08-21 01:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20190820_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusareaspagelink',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Something about focus areas', null=True),
        ),
    ]
