# Generated by Django 2.2.4 on 2019-08-23 12:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('project', '0020_auto_20190821_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusareaspagelink',
            name='first_project_page',
        ),
        migrations.RemoveField(
            model_name='focusareaspagelink',
            name='second_project_page',
        ),
        migrations.AddField(
            model_name='focusareaspagelink',
            name='projects',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock(required=True))], blank=True, null=True, verbose_name='Projects'),
        ),
        migrations.CreateModel(
            name='FocusAreasProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('other_page', models.ForeignKey(blank=True, help_text='A page to link to in the "Other Pages or Related Links" section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas_projects', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
