# Generated by Django 2.2.4 on 2019-08-23 14:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20190823_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusareaspagelink',
            name='projects',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock(page_type=['project.ProjectPage'], required=True))], blank=True, null=True, verbose_name='Projects'),
        ),
    ]
