# Generated by Django 2.2.3 on 2019-08-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20190830_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusareaspage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='More about', max_length=255, null=True, verbose_name='Section Title'),
        ),
    ]
