# Generated by Django 2.2.3 on 2019-08-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_focusareaspage_other_pages_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FocusAreasPageRelatedLink',
        ),
    ]
