# Generated by Django 2.2.3 on 2019-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20190830_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='Related content', max_length=255, null=True, verbose_name='Section Title'),
        ),
    ]
