# Generated by Django 3.0.7 on 2020-06-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20191125_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusareasprojects',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='projectpagerelatedlink',
            options={'ordering': ['sort_order']},
        ),
    ]
