# Generated by Django 3.2.16 on 2023-03-02 01:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('project', '0047_auto_20221012_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusareaspagelink',
            options={},
        ),
        migrations.RemoveField(
            model_name='focusareaspagelink',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='focusareaspagelink',
            name='related_page_handler',
            field=models.CharField(choices=[('manual', 'Manual'), ('topic', 'Topic')], default='manual', max_length=253, verbose_name='Show By'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='This date will be used for display and ordering'),
        ),
        migrations.AlterField(
            model_name='focusareaspagelink',
            name='projects',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock(required=True))], blank=True, null=True, use_json_field=True, verbose_name='Projects'),
        ),
        migrations.CreateModel(
            name='FocusAreasPageLinkTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas_page_link_topics', to='project.focusareaspagelink')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_focusareaspagelinktopic_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='focusareaspagelink',
            name='topics',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='project.FocusAreasPageLinkTopic', to='taggit.Tag', verbose_name='Topics'),
        ),
    ]
