# Generated by Django 3.2.16 on 2023-03-02 02:00

from django.db import migrations


def add_published_date(apps, schema_editor):
    Project = apps.get_model('project', 'ProjectPage')
    for project in Project.objects.all():
        if project.first_published_at is not None:
            project.published_date = project.first_published_at
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_auto_20230302_0159'),
    ]

    operations = [
        migrations.RunPython(add_published_date),
    ]
