# Generated by Django 3.2.15 on 2023-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_focusareaspagelink_related_page_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusareaspagelink',
            name='related_page_section_title',
            field=models.CharField(blank=True, default='Key projects and publications', max_length=255, verbose_name='Section Title'),
        ),
    ]
