# Generated by Django 3.2.19 on 2023-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_auto_20230603_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focusareaspagelink',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='focusareaspagelink',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
