# Generated by Django 2.2.3 on 2019-08-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20190809_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='placespage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='More about', max_length=255, verbose_name='Heading'),
        ),
    ]
