# Generated by Django 2.2.2 on 2019-11-22 16:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0020_auto_20191122_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placespage',
            name='places',
            field=wagtail.core.fields.StreamField([('place', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('subtitle', wagtail.core.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'anchor'], icon='fa-paragraph', template='blocks/paragraph_block.html')), ('side_section_title', wagtail.core.blocks.TextBlock(required=False)), ('links', wagtail.core.blocks.StreamBlock([('link', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(help_text='Leave blank if you wish to use the page title as a caption', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='For the link/button to show, either this or the url are required', required=False)), ('url', wagtail.core.blocks.URLBlock(help_text='An alternative to an internal page', required=False))]))], required=False))]))], blank=True, null=True, verbose_name='Places'),
        ),
    ]
