# Generated by Django 2.2.4 on 2019-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforuspage',
            name='other_pages_heading',
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='gdr_policy',
            field=models.URLField(blank=True, help_text='A Link to the GDR policy if any', null=True, verbose_name='GDR Policy'),
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='recruitment_policy',
            field=models.URLField(blank=True, help_text='A Link to the recruitment policy if any', null=True, verbose_name='Recruitment Policy'),
        ),
    ]
