# Generated by Django 2.2.4 on 2019-09-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0002_auto_20190923_1247'),
        ('workforus', '0002_auto_20190923_0925'),
    ]

    operations = [
    ]
