# Generated by Django 2.2.4 on 2019-08-21 14:02

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0002_auto_20190821_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforuspage',
            name='benefits',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.TextBlock()), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], blank=True, null=True, verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='gdr_policy',
            field=models.URLField(blank=True, help_text='A Link to the GDPR policy if any', null=True, verbose_name='GDPR Policy'),
        ),
    ]
