# Generated by Django 2.2.3 on 2019-09-25 14:20

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0002_auto_20190923_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforuspage',
            name='team_story',
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='team_stories',
            field=wagtail.core.fields.StreamField([('team_story_page', wagtail.core.blocks.PageChooserBlock(page_type=['general.General'], verbose_name='Story Page'))], blank=True, null=True, verbose_name='Team Stories'),
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='team_story_section_heading',
            field=models.CharField(blank=True, default='Team stories', max_length=255, verbose_name='Section Heading'),
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='team_story_section_sub_heading',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Section Sub-heading'),
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='benefits',
            field=wagtail.core.fields.StreamField([('benefit', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('logo', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='value_section_heading',
            field=models.CharField(blank=True, default='Our values', max_length=255, verbose_name='Value Heading'),
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='value_section_sub_heading',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Value Sub-heading'),
        ),
    ]
