# Generated by Django 2.2.3 on 2019-09-25 14:24

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0003_auto_20190925_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforuspage',
            name='vacancy_subtitle_text',
        ),
        migrations.RemoveField(
            model_name='workforuspage',
            name='vacancy_title',
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='vacancy_section_heading',
            field=models.TextField(blank=True, max_length=255, verbose_name='Section Heading'),
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='vacancy_section_sub_heading',
            field=models.TextField(blank=True, help_text='A brief description of the section contents', max_length=255, verbose_name='Section Sub-heading'),
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='team_story_section_sub_heading',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A brief description of the section contents', verbose_name='Section Sub-heading'),
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='value_section_sub_heading',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A brief description of the section contents', verbose_name='Value Sub-heading'),
        ),
    ]
