# Generated by Django 2.2.3 on 2019-09-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0006_auto_20190926_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforuspage',
            name='vacancy_section_heading',
            field=models.TextField(blank=True, default='Latest vacancies', max_length=255, verbose_name='Section Heading'),
        ),
    ]
