# Generated by Django 2.2.4 on 2019-09-26 05:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0006_auto_20190926_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforuspage',
            name='logos',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, verbose_name='Logos'),
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='benefits',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, verbose_name='Benefits'),
        ),
    ]
