# Generated by Django 2.2.4 on 2019-08-23 12:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0007_auto_20190823_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforuspage',
            name='benefits',
            field=wagtail.core.fields.StreamField([], blank=True, null=True, verbose_name='Benefits'),
        ),
    ]
