# Generated by Django 2.2.3 on 2019-09-26 07:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0007_auto_20190926_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforuspage',
            name='vacancy_section_sub_heading',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A brief description of the section contents', verbose_name='Section Sub-heading'),
        ),
    ]
