# Generated by Django 2.2.2 on 2019-09-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0008_auto_20190926_0754'),
        ('workforus', '0002_auto_20190920_1501'),
    ]

    operations = [
    ]
