# Generated by Django 2.2.4 on 2019-08-26 09:18

from django.db import migrations
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0009_auto_20190823_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforuspage',
            name='logos',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, verbose_name='Logos'),
        ),
    ]
