# Generated by Django 2.2.4 on 2019-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0011_auto_20190826_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Value Name')),
                ('paragraph', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='workforuspage',
            name='values',
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='values_text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Descriptve text for values section'),
        ),
    ]
