# Generated by Django 2.2.4 on 2019-08-26 12:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0012_auto_20190826_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='values',
            options={'verbose_name': 'Our Value', 'verbose_name_plural': 'Our Values'},
        ),
        migrations.AlterField(
            model_name='values',
            name='paragraph',
            field=wagtail.core.fields.RichTextField(max_length=255, verbose_name='Description'),
        ),
    ]
