# Generated by Django 2.2.4 on 2019-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0013_auto_20190826_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='paragraph',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
    ]
