# Generated by Django 2.2.4 on 2019-08-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0014_auto_20190826_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforuspage',
            name='values_text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Brief text for values section'),
        ),
    ]
