# Generated by Django 2.2.4 on 2019-08-27 12:07

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0015_auto_20190826_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforuspage',
            name='team_story',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, verbose_name='Team Stories'),
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='team_story_heading',
            field=models.TextField(blank=True, max_length=255, verbose_name='Brief text for the team story section'),
        ),
    ]
