# Generated by Django 2.2.4 on 2019-08-27 12:13

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0016_auto_20190827_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforuspage',
            name='team_story',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('story_url', wagtail.core.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, verbose_name='Team Stories'),
        ),
        migrations.AlterField(
            model_name='workforuspage',
            name='team_story_heading',
            field=models.TextField(blank=True, max_length=255, verbose_name='Brief descriptive text'),
        ),
    ]
