# Generated by Django 2.2.4 on 2019-08-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0017_auto_20190827_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforuspage',
            name='vacancy_heading',
            field=models.TextField(blank=True, max_length=255, verbose_name='Brief descriptive text for vacancies'),
        ),
    ]
