# Generated by Django 2.2.4 on 2019-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0019_auto_20190905_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values',
            old_name='paragraph',
            new_name='excerpt',
        ),
        migrations.AlterField(
            model_name='values',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
