# Generated by Django 2.2.4 on 2019-09-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0021_auto_20190906_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforuspage',
            name='logos',
        ),
    ]
