# Generated by Django 2.2.4 on 2019-09-06 11:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0023_auto_20190906_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforuspage',
            name='benefits',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('logos', wagtail.core.blocks.StreamBlock([('item', wagtail.images.blocks.ImageChooserBlock(required=False))]))]))], blank=True, null=True, verbose_name='Benefits'),
        ),
    ]
