# Generated by Django 2.2.4 on 2019-09-06 12:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0024_auto_20190906_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforuspage',
            name='benefits',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('logos', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))]))], blank=True, null=True, verbose_name='Benefits'),
        ),
    ]
