# Generated by Django 2.2.4 on 2019-09-08 22:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0027_auto_20190908_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforuspage',
            name='team_story',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock()), ('subtitle_text', wagtail.core.blocks.TextBlock()), ('stories', wagtail.core.blocks.StreamBlock([('team_story_page', wagtail.core.blocks.PageChooserBlock(required=False))]))]))], blank=True, null=True, verbose_name='Team Stories'),
        ),
    ]
