# Generated by Django 2.2.4 on 2019-09-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0028_auto_20190908_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workforuspage',
            old_name='vacancy_heading',
            new_name='vacancy_subtitle_text',
        ),
        migrations.AddField(
            model_name='workforuspage',
            name='vacancy_title',
            field=models.TextField(blank=True, max_length=255, verbose_name='Vacancy Title'),
        ),
    ]
