# Generated by Django 2.2.4 on 2019-09-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforus', '0029_auto_20190909_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforuspage',
            name='gdr_policy',
        ),
        migrations.RemoveField(
            model_name='workforuspage',
            name='recruitment_policy',
        ),
    ]
