# Generated by Django 2.2.4 on 2019-09-24 09:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasectionpage',
            name='quotes',
            field=wagtail.core.fields.StreamField([('team_member', wagtail.core.blocks.StructBlock([('team_member', wagtail.core.blocks.StreamBlock([('member', wagtail.core.blocks.PageChooserBlock(page_type=['ourteam.TeamMemberPage'], required=False))]))])), ('external_member', wagtail.core.blocks.StructBlock([('quote_text', wagtail.core.blocks.TextBlock()), ('role', wagtail.core.blocks.TextBlock()), ('organisation', wagtail.core.blocks.TextBlock()), ('external_member_photo', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, verbose_name='Quotes'),
        ),
    ]
