# Generated by Django 2.2.4 on 2019-09-25 04:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0003_auto_20190924_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasectionpage',
            name='quotes',
            field=wagtail.core.fields.StreamField([('team_member', wagtail.core.blocks.StructBlock([('quote_text', wagtail.core.blocks.TextBlock()), ('team_member', wagtail.core.blocks.PageChooserBlock(page_type=['ourteam.TeamMemberPage'], required=False))])), ('external_member', wagtail.core.blocks.StructBlock([('quote_text', wagtail.core.blocks.TextBlock()), ('name', wagtail.core.blocks.TextBlock()), ('role', wagtail.core.blocks.TextBlock()), ('organisation', wagtail.core.blocks.TextBlock()), ('external_member_photo', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, verbose_name='Quotes'),
        ),
    ]
