# Generated by Django 2.2.2 on 2019-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0005_auto_20191105_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='date_of_access',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='lead_analyst',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='license',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datasource',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='geography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='organisation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
