# Generated by Django 2.2.4 on 2019-09-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0005_datasectionpage_dataset_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasectionpage',
            name='dataset_subtitle',
            field=models.TextField(default='', help_text='A description of the datasets'),
        ),
    ]
