# Generated by Django 2.2.2 on 2019-11-07 17:04

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0006_auto_20191107_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetpage',
            name='csv_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='dataset_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='dataset_title',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='xlsx_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='figurepage',
            name='csv_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='figurepage',
            name='dataset_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='figurepage',
            name='dataset_title',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='figurepage',
            name='xlsx_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='meta_data',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.TextBlock(required=True)), ('provenance', wagtail.blocks.TextBlock()), ('variables', wagtail.blocks.TextBlock()), ('geography', wagtail.blocks.TextBlock()), ('geograpic_coding', wagtail.blocks.TextBlock()), ('unit', wagtail.blocks.TextBlock()), ('internal_notes', wagtail.blocks.TextBlock()), ('lead_analyst', wagtail.blocks.TextBlock()), ('licence', wagtail.blocks.TextBlock()), ('citation', wagtail.blocks.TextBlock())], help_text='A description is expected, but only one of each shall be shown', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='figurepage',
            name='meta_data',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.TextBlock(required=True)), ('provenance', wagtail.blocks.TextBlock()), ('variables', wagtail.blocks.TextBlock()), ('geography', wagtail.blocks.TextBlock()), ('geograpic_coding', wagtail.blocks.TextBlock()), ('unit', wagtail.blocks.TextBlock()), ('internal_notes', wagtail.blocks.TextBlock()), ('lead_analyst', wagtail.blocks.TextBlock()), ('licence', wagtail.blocks.TextBlock()), ('citation', wagtail.blocks.TextBlock())], help_text='A description is expected, but only one of each shall be shown', verbose_name='Content'),
        ),
    ]
