# Generated by Django 2.2.4 on 2019-09-25 08:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0008_auto_20190925_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasectionpage',
            name='data_support',
            field=wagtail.core.fields.StreamField([('support', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('description', wagtail.core.blocks.TextBlock()), ('telephone', wagtail.core.blocks.TextBlock()), ('email', wagtail.core.blocks.EmailBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('photo_credit', wagtail.core.blocks.URLBlock())]))], blank=True, null=True, verbose_name='Quotes'),
        ),
    ]
