# Generated by Django 2.2.2 on 2019-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0009_auto_20191107_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasectionpage',
            name='dataset_info',
            field=models.TextField(blank=True, help_text='A description of the datasets', null=True),
        ),
    ]
