# Generated by Django 2.2.2 on 2019-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0010_auto_20191107_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurepage',
            name='name',
            field=models.TextField(blank=True, help_text='The name of this figure in the publication e.g Figure 1.1', null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='figurepage',
            name='publication_name',
            field=models.TextField(blank=True, help_text='Imported publication name', null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='figurepage',
            name='related_figures_title',
            field=models.CharField(blank=True, default='Related figures', max_length=255, null=True, verbose_name='Section Title'),
        ),
    ]
