# Generated by Django 2.2.4 on 2019-10-02 13:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0011_datasectionrelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasectionpage',
            name='data_support',
            field=wagtail.core.fields.StreamField([('support', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('description', wagtail.core.blocks.TextBlock(required=False)), ('telephone', wagtail.core.blocks.TextBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('photographer', wagtail.core.blocks.TextBlock(required=False)), ('photo_credit', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True, verbose_name='Data Support Services'),
        ),
    ]
