# Generated by Django 2.2.2 on 2019-11-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0011_auto_20191107_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='license',
        ),
        migrations.AddField(
            model_name='datasource',
            name='licence',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
