# Generated by Django 2.2.2 on 2019-11-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0007_auto_20191107_1356'),
        ('datasection', '0012_auto_20191107_1914'),
    ]

    operations = [
    ]
