# Generated by Django 2.2.2 on 2019-11-14 14:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0013_merge_20191111_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='lead_analyst',
        ),
        migrations.RemoveField(
            model_name='figurepage',
            name='publication_name',
        ),
        migrations.AddField(
            model_name='datasource',
            name='authors',
            field=wagtail.core.fields.StreamField([('internal_author', wagtail.core.blocks.PageChooserBlock(icon='fa-user', page_type=['ourteam.TeamMemberPage'], required=False)), ('external_author', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('photograph', wagtail.images.blocks.ImageChooserBlock(required=False)), ('page', wagtail.core.blocks.URLBlock(required=False))], icon='fa-user'))], blank=True),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='meta_data',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.TextBlock(required=True)), ('provenance', wagtail.core.blocks.TextBlock(required=False)), ('variables', wagtail.core.blocks.TextBlock(required=False)), ('geography', wagtail.core.blocks.TextBlock(required=False)), ('geograpic_coding', wagtail.core.blocks.TextBlock(required=False)), ('unit', wagtail.core.blocks.TextBlock(required=False)), ('internal_notes', wagtail.core.blocks.TextBlock(required=False)), ('licence', wagtail.core.blocks.TextBlock(required=False)), ('citation', wagtail.core.blocks.TextBlock(required=False))], help_text='A description is expected, but only one of each shall be shown', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='figurepage',
            name='meta_data',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.TextBlock(required=True)), ('provenance', wagtail.core.blocks.TextBlock(required=False)), ('variables', wagtail.core.blocks.TextBlock(required=False)), ('geography', wagtail.core.blocks.TextBlock(required=False)), ('geograpic_coding', wagtail.core.blocks.TextBlock(required=False)), ('unit', wagtail.core.blocks.TextBlock(required=False)), ('internal_notes', wagtail.core.blocks.TextBlock(required=False)), ('licence', wagtail.core.blocks.TextBlock(required=False)), ('citation', wagtail.core.blocks.TextBlock(required=False))], help_text='A description is expected, but only one of each shall be shown', verbose_name='Content'),
        ),
    ]
