# Generated by Django 2.2.3 on 2019-10-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0014_auto_20191017_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasectionpage',
            old_name='dataset_subtitle',
            new_name='dataset_info',
        ),
    ]
