# Generated by Django 2.2.2 on 2019-11-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0014_auto_20191114_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurepage',
            name='publication',
        ),
    ]
