# Generated by Django 2.2.2 on 2019-11-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0015_remove_figurepage_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurepage',
            name='report_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
