# Generated by Django 2.2.2 on 2019-11-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('datasection', '0016_figurepage_report_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurepage',
            name='report_title',
        ),
        migrations.AddField(
            model_name='figurepage',
            name='publication',
            field=models.ForeignKey(blank=True, help_text='The publication in which this figure appears', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
