# Generated by Django 2.2.3 on 2019-10-17 08:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0016_datasetlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetlisting',
            name='hero_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A description of the page content', null=True),
        ),
    ]
