# Generated by Django 2.2.3 on 2019-10-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0018_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('date_of_access', models.DateField(blank=True)),
                ('link_to_metadata', models.URLField(blank=True)),
                ('geography', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Optional. Will be auto-generated from title if left blank.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, help_text='Optional. Will be auto-generated from title if left blank.', max_length=255, null=True),
        ),
    ]
