# Generated by Django 2.2.6 on 2019-11-20 06:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0020_auto_20191118_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpage',
            name='meta_data',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.RichTextBlock(required=True)), ('provenance', wagtail.core.blocks.RichTextBlock(required=False)), ('variables', wagtail.core.blocks.RichTextBlock(required=False)), ('geography', wagtail.core.blocks.RichTextBlock(required=False)), ('geograpic_coding', wagtail.core.blocks.RichTextBlock(required=False)), ('unit', wagtail.core.blocks.RichTextBlock(required=False)), ('internal_notes', wagtail.core.blocks.RichTextBlock(required=False)), ('licence', wagtail.core.blocks.RichTextBlock(required=False)), ('citation', wagtail.core.blocks.RichTextBlock(required=False, template='blocks/urlize_richtext.html'))], help_text='A description is expected, but only one of each shall be shown', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='figurepage',
            name='meta_data',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.RichTextBlock(required=True)), ('provenance', wagtail.core.blocks.RichTextBlock(required=False)), ('variables', wagtail.core.blocks.RichTextBlock(required=False)), ('geography', wagtail.core.blocks.RichTextBlock(required=False)), ('geograpic_coding', wagtail.core.blocks.RichTextBlock(required=False)), ('unit', wagtail.core.blocks.RichTextBlock(required=False)), ('internal_notes', wagtail.core.blocks.RichTextBlock(required=False)), ('licence', wagtail.core.blocks.RichTextBlock(required=False)), ('citation', wagtail.core.blocks.RichTextBlock(required=False, template='blocks/urlize_richtext.html'))], help_text='A description is expected, but only one of each shall be shown', verbose_name='Content'),
        ),
    ]
