# Generated by Django 2.2.2 on 2019-11-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0021_auto_20191118_2113'),
        ('datasection', '0021_auto_20191120_0636'),
    ]

    operations = [
    ]
