# Generated by Django 2.2.3 on 2019-10-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0021_auto_20191017_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetpage',
            name='publication_type',
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='publication',
            field=models.CharField(blank=True, help_text='The publication that used this dataset. For a figure, format is [Publication] - [Figure] e.g ITEP 2018 - Figure 1.1', max_length=255, verbose_name='Publication Type'),
        ),
    ]
