# Generated by Django 2.2.3 on 2019-10-18 07:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0022_auto_20191018_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetpage',
            name='text_content',
        ),
        migrations.AddField(
            model_name='datasetpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('internal_author', wagtail.core.blocks.PageChooserBlock(icon='fa-user', page_type=['ourteam.TeamMemberPage'], required=False)), ('external_author', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('photograph', wagtail.images.blocks.ImageChooserBlock(required=False)), ('page', wagtail.core.blocks.URLBlock(required=False))], icon='fa-user'))], blank=True),
        ),
    ]
