# Generated by Django 2.2.3 on 2019-10-18 08:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('datasection', '0023_auto_20191018_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetDownloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional: document title, defaults to the file name if left blank', max_length=255)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_downloads', to='datasection.DatasetPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
