# Generated by Django 2.2.4 on 2019-11-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0023_auto_20191121_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetlisting',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='datasetlisting',
            name='hero_image_credit_name',
        ),
        migrations.RemoveField(
            model_name='datasetlisting',
            name='hero_image_credit_url',
        ),
        migrations.RemoveField(
            model_name='datasetlisting',
            name='hero_link',
        ),
        migrations.RemoveField(
            model_name='datasetlisting',
            name='hero_link_caption',
        ),
        migrations.RemoveField(
            model_name='datasetlisting',
            name='search_image',
        ),
    ]
