# Generated by Django 2.2.3 on 2019-10-18 11:57

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0024_datasetdownloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='link_to_data',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='meta_data',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.RichTextBlock(required=True)), ('provenance', wagtail.core.blocks.RichTextBlock()), ('variables', wagtail.core.blocks.RichTextBlock()), ('geography', wagtail.core.blocks.RichTextBlock()), ('licence', wagtail.core.blocks.RichTextBlock()), ('citation', wagtail.core.blocks.RichTextBlock())], default='', help_text='A description is expected, but only one of each shall be shown', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
