# Generated by Django 2.2.4 on 2019-11-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0025_datasetlisting_search_image'),
        ('datasection', '0023_datasetlisting_search_image'),
    ]

    operations = [
    ]
