# Generated by Django 2.2.3 on 2019-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0025_auto_20191018_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetpage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='More about', max_length=255, verbose_name='Heading'),
        ),
    ]
