# Generated by Django 2.2.3 on 2019-10-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0026_datasetpage_other_pages_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoreAboutRelatedLink',
        ),
    ]
