# Generated by Django 2.2.4 on 2020-04-19 13:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('datasection', '0026_auto_20191126_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasectionpage',
            name='button_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country spotlight button label'),
        ),
        migrations.AddField(
            model_name='datasectionpage',
            name='button_url',
            field=models.URLField(blank=True, verbose_name='Country spotlight button URL'),
        ),
        migrations.AddField(
            model_name='datasectionpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Country spotlight content', null=True),
        ),
        migrations.AddField(
            model_name='datasectionpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Country spotlight image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='datasectionpage',
            name='spotlights_title',
            field=models.TextField(blank=True, help_text='Country spotlight title', null=True),
        ),
    ]
