# Generated by Django 2.2.3 on 2019-10-18 13:28

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0027_delete_moreaboutrelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpagerelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_dataset_links', to='datasection.DatasetPage'),
        ),
        migrations.DeleteModel(
            name='TeamMemberRelatedLink',
        ),
    ]
