# Generated by Django 2.2.4 on 2020-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0027_auto_20200419_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasectionpage',
            name='image_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtitle for spotlight image'),
        ),
    ]
