# Generated by Django 2.2.4 on 2020-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0028_datasectionpage_image_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasectionpage',
            name='image_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Image Subtitle'),
        ),
    ]
