# Generated by Django 2.2.3 on 2019-10-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0029_auto_20191021_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpage',
            name='publication',
            field=models.CharField(blank=True, help_text='The publication that used this dataset. For a figure, format is [Publication] - [Figure] e.g ITEP 2018 - Figure 1.1', max_length=255, verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='datasetpage',
            name='related_datasets_title',
            field=models.CharField(blank=True, default='Related datasets', max_length=255, verbose_name='Section Title'),
        ),
    ]
