# Generated by Django 2.2.4 on 2020-04-19 13:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0029_auto_20200419_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasectionpage',
            name='button_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Button label'),
        ),
        migrations.AlterField(
            model_name='datasectionpage',
            name='button_url',
            field=models.URLField(blank=True, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='datasectionpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Spotlight content', null=True),
        ),
        migrations.AlterField(
            model_name='datasectionpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Spotlight image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='datasectionpage',
            name='spotlights_title',
            field=models.TextField(blank=True, help_text='Heading', null=True),
        ),
    ]
