# Generated by Django 2.2.4 on 2020-04-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0030_auto_20200419_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasectionpage',
            name='spotlights_title',
        ),
        migrations.AddField(
            model_name='datasectionpage',
            name='spotlights_heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
