# Generated by Django 2.2.3 on 2019-10-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0030_auto_20191021_1011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RemoveField(
            model_name='datasetpage',
            name='report',
        ),
    ]
