# Generated by Django 2.2.3 on 2019-10-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0032_auto_20191023_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='date_of_access',
        ),
    ]
