# Generated by Django 2.2.3 on 2019-10-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0034_auto_20191025_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetpage',
            options={'verbose_name': 'Data Set Page'},
        ),
        migrations.AlterModelOptions(
            name='figurepage',
            options={'verbose_name': 'Figure Page'},
        ),
        migrations.RemoveField(
            model_name='datasetpage',
            name='publication',
        ),
    ]
