# Generated by Django 2.2.6 on 2019-10-28 15:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0036_auto_20191025_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigureDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('dataset', models.ForeignKey(blank=True, help_text='A dataset on which this figure is based', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='datasection.DatasetPage', verbose_name='Data Set')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure_datasets', to='datasection.FigurePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
