# Generated by Django 2.2.16 on 2020-10-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0040_auto_20200717_1207'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0065_auto_20200702_1244'),
        ('common', '0006_auto_20190924_0826'),
        ('wagtaillinkchecker', '0005_auto_20180922_1835'),
        ('events', '0032_auto_20200702_1244'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('project', '0043_auto_20200702_1244'),
        ('publications', '0074_auto_20200924_1610'),
        ('news', '0032_auto_20200702_1244'),
        ('datasection', '0042_auto_20200702_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='figurepage',
            name='hero_link',
        ),
        migrations.RemoveField(
            model_name='figurepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='figurepage',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='figurepage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='figurepage',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='figurepagedownloads',
            name='file',
        ),
        migrations.RemoveField(
            model_name='figurepagedownloads',
            name='page',
        ),
        migrations.RemoveField(
            model_name='figurepagerelatedlink',
            name='other_page',
        ),
        migrations.RemoveField(
            model_name='figurepagerelatedlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='figuresource',
            name='page',
        ),
        migrations.RemoveField(
            model_name='figuresource',
            name='source',
        ),
        migrations.RemoveField(
            model_name='figuretopic',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='figuretopic',
            name='tag',
        ),
        migrations.DeleteModel(
            name='FigureDataSet',
        ),
        migrations.DeleteModel(
            name='FigurePage',
        ),
        migrations.DeleteModel(
            name='FigurePageDownloads',
        ),
        migrations.DeleteModel(
            name='FigurePageRelatedLink',
        ),
        migrations.DeleteModel(
            name='FigureSource',
        ),
        migrations.DeleteModel(
            name='FigureTopic',
        ),
    ]
