# Generated by Django 2.2.16 on 2020-10-14 18:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasection', '0043_auto_20201002_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetPageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Optional. Will be auto-generated from name if left blank.', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data topics',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='datasetpage',
            name='topics',
        ),
        migrations.DeleteModel(
            name='DataSetTopic',
        ),
        migrations.AddField(
            model_name='datasetpagetopic',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_topics', to='datasection.DatasetPage'),
        ),
        migrations.AddField(
            model_name='datasetpagetopic',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datasection.DataTopic'),
        ),
    ]
