# Generated by Django 2.2.2 on 2019-07-25 10:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Something about our newsletters', null=True),
        ),
    ]
