# Generated by Django 2.2.3 on 2019-07-31 14:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('news', '0002_newsindexpage_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspagerelatedlink',
            options={},
        ),
        migrations.RemoveField(
            model_name='newspagerelatedlink',
            name='related_link',
        ),
        migrations.AddField(
            model_name='newspagerelatedlink',
            name='other_page',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to in the "Other Pages" section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Other Page'),
        ),
        migrations.AlterField(
            model_name='newspagerelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_related_links', to='wagtailcore.Page'),
        ),
    ]
