# Generated by Django 2.2.2 on 2019-08-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20190819_1017'),
        ('news', '0009_auto_20190815_1902'),
    ]

    operations = [
    ]
