# Generated by Django 2.2.3 on 2019-08-28 16:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20190828_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacenterpage',
            name='spokespeople',
            field=wagtail.fields.StreamField([('person', wagtail.blocks.StructBlock([('person', wagtail.blocks.PageChooserBlock(page_type=['ourteam.TeamMemberPage'], required=False))]))], blank=True, null=True),
        ),
    ]
