# Generated by Django 2.2.10 on 2020-03-31 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20191125_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstorypage',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='This date will be used for display and ordering'),
        ),
    ]
