# Generated by Django 3.0.7 on 2020-06-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_newsstorypage_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspagerelatedlink',
            options={'ordering': ['sort_order']},
        ),
    ]
