# Generated by Django 3.0.7 on 2020-06-11 13:20

from django.db import migrations
from django.utils.functional import cached_property
from django.forms import CharField, Media

import wagtail.core.fields
from wagtail.core.blocks import FieldBlock
from wagtail.admin.staticfiles import versioned_static

from di_website.visualisation.fields import AceEditorInput


class ChartBlock(FieldBlock):

    def __init__(self, *args, **kwargs):
        super(ChartBlock, self).__init__(*args, **kwargs)

    @cached_property
    def field(self):
        return CharField(widget=AceEditorInput(editor_options={}))


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0002_chartpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpage',
            name='charts',
            field=wagtail.core.fields.StreamField([('chart', ChartBlock())], blank=True),
        ),
    ]
