# Generated by Django 3.0.7 on 2020-06-11 13:20

import di_website.visualisation.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0002_chartpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpage',
            name='charts',
            field=wagtail.core.fields.StreamField([('chart', di_website.visualisation.blocks.ChartBlock())], blank=True),
        ),
    ]
