# Generated by Django 3.0.7 on 2020-06-17 20:44

import di_website.visualisation.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0003_chartpage_charts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartpage',
            name='charts',
        ),
        migrations.AddField(
            model_name='chartpage',
            name='chart',
            field=di_website.visualisation.fields.AceEditorField(blank=True),
        ),
    ]
