# Generated by Django 3.0.7 on 2020-06-17 21:01

import di_website.visualisation.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0004_auto_20200617_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartpage',
            name='chart',
            field=di_website.visualisation.fields.AceEditorJSONField(blank=True, default='{"data":[], "layout":{}}'),
        ),
    ]
