# Generated by Django 3.0.7 on 2020-06-18 13:02

import di_website.visualisation.fields
import di_website.visualisation.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0005_auto_20200617_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartpage',
            name='chart',
        ),
        migrations.AddField(
            model_name='chartpage',
            name='chart_json',
            field=di_website.visualisation.fields.AceEditorField(blank=True, default=di_website.visualisation.models.default_chart_json, verbose_name='Chart JSON'),
        ),
    ]
