# Generated by Django 3.0.7 on 2020-06-18 20:42

import di_website.visualisation.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0006_auto_20200618_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartpage',
            name='chart_json',
            field=di_website.visualisation.fields.AceEditorField(blank=True, default='{ "data":[], "layout":{} }', verbose_name='Chart JSON'),
        ),
    ]
