# Generated by Django 2.2.13 on 2020-07-06 10:33

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0009_chartpage_fallback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpage',
            name='display_fallback_mobile',
            field=models.BooleanField(default=True, help_text='Optional: when selected devices with screen widths up to 400px will be served the fallback image'),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='display_fallback_tablet',
            field=models.BooleanField(default=False, help_text='Optional: when selected devices with screen widths up to 700px will be served the fallback image'),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='display_general_instructions',
            field=models.BooleanField(default=True, help_text='Optional: display the general visualisation instructions, edited on the visualisations parent page'),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='instructions',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='visualisationspage',
            name='instructions',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
