# Generated by Django 2.2.13 on 2020-07-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0010_auto_20200706_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisationspage',
            name='larger_screen_text',
            field=models.CharField(default='To view this interactive visualisation use a device with a larger screen.', help_text="Text that is displayed for individual charts when the user's screen is less than the minimum width defined in the chart page", max_length=255),
        ),
        migrations.AddField(
            model_name='visualisationspage',
            name='no_js_text',
            field=models.CharField(default='To view this interactive visualisation make sure JavaScript is available on your device.', help_text='Text that is displayed for all charts when the user does not have JavaScript available', max_length=255),
        ),
    ]
