# Generated by Django 2.2.13 on 2020-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0012_auto_20200715_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpage',
            name='aggregation_excludes',
            field=models.TextField(default=False, help_text='Optional: comma separated values to exclude in the aggregated chart. Use when exclusions are fewer than inclusions'),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='aggregation_includes',
            field=models.TextField(default=False, help_text='Optional: comma separated values to include in the aggregated chart. Use when inclusions are fewer than exclusions'),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='selector_excludes',
            field=models.TextField(default=False, help_text='Optional: comma separated values to exclude in the dropdown selector. Use when exclusions are fewer than inclusions'),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='selector_includes',
            field=models.TextField(default=False, help_text='Optional: comma separated values to include in the dropdown selector. Use when inclusions are fewer than exclusions'),
        ),
    ]
