# Generated by Django 2.2.13 on 2020-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0014_auto_20200715_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpage',
            name='aggregate_option_label',
            field=models.CharField(blank=True, default='All data', help_text='The label of the "All data" option on aggregated charts', max_length=255, null=True),
        ),
    ]
