# Generated by Django 2.2.13 on 2020-07-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0015_chartpage_aggregate_option_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpage',
            name='y_axis_prefix',
            field=models.CharField(blank=True, help_text='Optional: e.g. UGX, $ e.t.c', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='y_axis_suffix',
            field=models.CharField(blank=True, help_text='Optional: e.g. %, degrees e.t.c', max_length=200, null=True),
        ),
    ]
