# Generated by Django 2.2.13 on 2020-07-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0016_auto_20200715_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpage',
            name='instructions_heading',
            field=models.TextField(blank=True, default='Interactive visualisation instructions', verbose_name='Accordion heading'),
        ),
        migrations.AlterField(
            model_name='chartpage',
            name='display_general_instructions',
            field=models.BooleanField(default=True, help_text='Optional: display the general visualisation instructions, edited on the visualisations parent page', verbose_name='Show general instructions'),
        ),
    ]
