# Generated by Django 2.2.13 on 2020-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0017_auto_20200716_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpage',
            name='source',
            field=models.TextField(blank=True, help_text='Optional: appears in the image download at the bottom of the chart', null=True),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='title_in_image',
            field=models.TextField(blank=True, help_text='Optional: appears in image download at the bottom of the chart', null=True),
        ),
    ]
