# Generated by Django 3.1 on 2020-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0020_auto_20200717_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartpage',
            name='chart_json',
            field=models.JSONField(help_text='Paste exported Chart Studio JSON here. To preserve data integretity, the JSON data should not be edited in Wagtail', verbose_name='Chart JSON'),
        ),
    ]
