# Generated by Django 3.1 on 2020-09-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0020_auto_20200717_1009'),
    ]

    operations = []
