# Generated by Django 3.1 on 2020-09-08 06:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0021_auto_20200903_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartpage',
            name='chart_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Paste exported Chart Studio JSON here. To preserve data integretity, the JSON data should not be edited in Wagtail', verbose_name='Chart JSON'),
        ),
    ]
