# Generated by Django 2.2.16 on 2020-09-23 13:48

import di_website.visualisation.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('visualisation', '0022_auto_20200908_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedChartPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('javascript', di_website.visualisation.fields.AceEditorJSONField()),
            ],
            options={
                'verbose_name': 'Advanced Chart Page',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterModelOptions(
            name='chartpage',
            options={'verbose_name': 'Plotly Studio Chart Page'},
        ),
    ]
