# Generated by Django 2.2.16 on 2020-09-23 15:03

import di_website.visualisation.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0023_auto_20200923_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedchartpage',
            name='javascript',
            field=di_website.visualisation.fields.AceEditorField(),
        ),
    ]
