# Generated by Django 2.2.16 on 2020-09-24 11:31

import di_website.visualisation.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0025_auto_20200923_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedchartpage',
            name='css',
            field=di_website.visualisation.fields.AceEditorField(blank=True, default='/* CSS goes here */'),
        ),
        migrations.AlterField(
            model_name='advancedchartpage',
            name='html',
            field=di_website.visualisation.fields.AceEditorField(blank=True, default='{% load wagtailcore_tags %}'),
        ),
        migrations.AlterField(
            model_name='advancedchartpage',
            name='javascript',
            field=di_website.visualisation.fields.AceEditorField(blank=True, default='"use strict";'),
        ),
    ]
