# Generated by Django 2.2.16 on 2020-09-24 12:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0029_advancedchartpage_use_d3'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchartpage',
            name='d3_modules',
            field=wagtail.core.fields.StreamField([('module', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(choices=[('colour', 'Colour'), ('interpolate', 'Interpolate'), ('scale-chromatic', 'Scale Chromatic')], label='Module')))], blank=True),
        ),
    ]
