# Generated by Django 2.2.16 on 2020-09-26 21:12

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0034_auto_20200924_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchartpage',
            name='caption',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Optional: caption text and link(s) for the chart', null=True),
        ),
        migrations.AddField(
            model_name='advancedchartpage',
            name='instructions',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='advancedchartpage',
            name='instructions_heading',
            field=models.TextField(blank=True, default='Interactive visualisation instructions', verbose_name='Accordion heading'),
        ),
    ]
