# Generated by Django 2.2.16 on 2021-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0038_auto_20201014_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchartpage',
            name='alternative_text',
            field=models.TextField(blank=True, help_text='Accessibility text for screen readers e.t.c', null=True),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='alternative_text',
            field=models.TextField(blank=True, help_text='Accessibility text for screen readers e.t.c', null=True),
        ),
    ]
