# Generated by Django 3.1 on 2021-09-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0039_auto_20210421_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartpage',
            name='chart_json',
            field=models.JSONField(help_text='Paste exported Chart Studio JSON here. To preserve data integretity, the JSON data should not be edited in Wagtail', verbose_name='Chart JSON'),
        ),
    ]
