# Generated by Django 3.2.7 on 2022-01-21 15:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('visualisation', '0042_rawcodepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotTable',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('instructions', wagtail.fields.RichTextField(blank=True)),
                ('instructions_heading', models.TextField(blank=True, default='Interactive visualisation instructions', verbose_name='Accordion heading')),
                ('caption', wagtail.fields.RichTextField(blank=True, help_text='Optional: caption text and link(s) for the chart', null=True)),
                ('data_source_url', models.TextField(help_text='Link to the CSV data file')),
                ('row_label', models.CharField(help_text='CSV column to show as the label for each table row', max_length=200)),
                ('column_label', models.CharField(help_text='CSV column to show as the label for each table column', max_length=200)),
                ('cell_value', models.CharField(help_text='CSV column whose data shall appear in the table cells', max_length=200)),
                ('show_row_total', models.BooleanField(blank=True, default=True)),
                ('show_column_total', models.BooleanField(blank=True, default=True)),
                ('filter_by', models.TextField(blank=True, help_text='Optional: taken from the CSV data file - comma separated column names to filter by', null=True)),
                ('default_filter_values', models.TextField(blank=True, help_text='Optional: Comma separated values to match the provided filters', null=True)),
                ('cell_highlight_condition', models.CharField(blank=True, choices=[('lt', 'Less Than'), ('gt', 'Greater Than')], default='lt', help_text='Optional: condition for highlighting cells', max_length=5, null=True)),
                ('cell_highlight_value', models.IntegerField(blank=True, help_text='Optional: value to conditionally highlight cells', null=True)),
                ('row_highlight_field', models.CharField(blank=True, help_text='Optional: column the value of which to conditionally highlight row', max_length=100, null=True)),
                ('row_highlight_condition', models.CharField(blank=True, choices=[('lt', 'Less Than'), ('gt', 'Greater Than')], default='lt', help_text='Optional: condition for highlighting a row', max_length=5, null=True)),
                ('row_highlight_value', models.IntegerField(blank=True, help_text='Optional: column value to conditionally highlight row', null=True)),
            ],
            options={
                'verbose_name': 'Pivot Table',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AlterModelOptions(
            name='rawcodepage',
            options={'verbose_name': 'Raw Code Snippet'},
        ),
    ]
