# Generated by Django 3.2.7 on 2022-01-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0044_auto_20220121_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivottable',
            name='cell_highlight_condition',
            field=models.CharField(blank=True, choices=[('lt', 'Less Than'), ('gt', 'Greater Than'), ('eq', 'Equals'), ('lte', 'Less Than or Equal'), ('gte', 'Greater Than or Equal')], default='lt', help_text='Optional: condition for highlighting cells', max_length=5, null=True, verbose_name='Cell Condition'),
        ),
        migrations.AlterField(
            model_name='pivottable',
            name='row_highlight_condition',
            field=models.CharField(blank=True, choices=[('lt', 'Less Than'), ('gt', 'Greater Than'), ('eq', 'Equals'), ('lte', 'Less Than or Equal'), ('gte', 'Greater Than or Equal')], default='lt', help_text='Optional: condition for highlighting a row', max_length=5, null=True, verbose_name='Condition'),
        ),
    ]
