# Generated by Django 3.2.7 on 2022-01-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0045_auto_20220121_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivottable',
            name='row_highlight_value',
            field=models.TextField(blank=True, help_text='Optional: column value to conditionally highlight row', null=True, verbose_name='Column value'),
        ),
    ]
