# Generated by Django 3.2.7 on 2022-01-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0046_alter_pivottable_row_highlight_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivottable',
            name='row_highlight_value',
            field=models.CharField(blank=True, help_text='Optional: column value to conditionally highlight row', max_length=200, null=True, verbose_name='Column value'),
        ),
    ]
