# Generated by Django 3.2.7 on 2022-01-25 12:07

import di_website.visualisation.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0049_alter_pivottable_row_label_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisationspage',
            name='footer_assets',
            field=di_website.visualisation.fields.AceEditorField(blank=True, default='{% load wagtailcore_tags %}', help_text='Optional: code that should be added to bottom of the document body e.g. JavaScript'),
        ),
        migrations.AddField(
            model_name='visualisationspage',
            name='header_assets',
            field=di_website.visualisation.fields.AceEditorField(blank=True, default='{% load wagtailcore_tags %}', help_text='Optional: code that should be added to document head e.g. CSS'),
        ),
    ]
