# Generated by Django 3.2.7 on 2022-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0054_auto_20220201_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivottablerowhighlight',
            name='row_highlight_colour',
            field=models.CharField(blank=True, default='#ffb3b3', help_text='Optional: HTML colour of highlighted row - when in doubt, refer to https://htmlcolors.com/', max_length=256),
        ),
    ]
