# Generated by Django 3.2.13 on 2022-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0055_alter_pivottablerowhighlight_row_highlight_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchartpage',
            name='instruction_position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=256, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='chartpage',
            name='instruction_position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=256, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='pivottable',
            name='instruction_position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=256, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='rawcodepage',
            name='instruction_position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=256, verbose_name='Position'),
        ),
    ]
