# Generated by Django 3.2.14 on 2022-07-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0056_auto_20220718_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisationspage',
            name='instruction_position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='bottom', max_length=256, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='visualisationspage',
            name='instructions_heading',
            field=models.TextField(blank=True, default='Interactive visualisation instructions', verbose_name='Accordion heading'),
        ),
    ]
