# Generated by Django 3.2.15 on 2022-10-07 10:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualisation', '0057_auto_20220720_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedchartpage',
            name='d3_modules',
            field=wagtail.fields.StreamField([('module', wagtail.blocks.ChoiceBlock(choices=[('colour', 'Colour'), ('interpolate', 'Interpolate'), ('scale-chromatic', 'Scale Chromatic')], label='Module'))], blank=True, use_json_field=True, verbose_name='D3 Modules'),
        ),
        migrations.AlterField(
            model_name='rawcodepage',
            name='d3_modules',
            field=wagtail.fields.StreamField([('module', wagtail.blocks.ChoiceBlock(choices=[('colour', 'Colour'), ('interpolate', 'Interpolate'), ('scale-chromatic', 'Scale Chromatic')], label='Module'))], blank=True, use_json_field=True, verbose_name='D3 Modules'),
        ),
    ]
