# Generated by Django 2.2.3 on 2019-08-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20190819_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whowearepage',
            name='locations',
        ),
    ]
