# Generated by Django 2.2.3 on 2019-08-19 10:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20190819_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstorypage',
            name='timeline_items',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('month', wagtail.blocks.CharBlock(help_text='Month abbreviation E.g. Apr', required=False)), ('year', wagtail.blocks.CharBlock(help_text='Year E.g. 2008', required=False)), ('title', wagtail.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False)), ('documents', wagtail.blocks.StructBlock([('document_box_heading', wagtail.blocks.CharBlock(icon='title', required=False)), ('documents', wagtail.blocks.StreamBlock([('document', wagtail.documents.blocks.DocumentChooserBlock())], required=False)), ('dark_mode', wagtail.blocks.BooleanBlock(default=False, help_text='Red on white if unchecked. White on dark grey if checked.', required=False))], required=False))]))]),
        ),
    ]
