# Generated by Django 2.2.3 on 2019-10-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_auto_20191023_0650'),
        ('about', '0018_auto_20191023_0700'),
    ]

    operations = [
    ]
