# Generated by Django 2.2.3 on 2019-10-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_auto_20191017_0512'),
        ('about', '0019_merge_20191023_0813'),
    ]

    operations = [
    ]
