# Generated by Django 2.2.3 on 2019-10-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_auto_20191025_1146'),
        ('about', '0021_auto_20191023_1012'),
    ]

    operations = [
    ]
