# Generated by Django 2.2.3 on 2019-07-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_download'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherPage',
        ),
    ]
