# Generated by Django 2.2.2 on 2019-09-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_delete_otherpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
