# Generated by Django 2.2.2 on 2019-06-28 15:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('show_navigation_links', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'footer section',
                'verbose_name_plural': 'footer sections',
            },
        ),
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Footer Text',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Sign up for our newsletter to receive regular news and updates', max_length=255)),
                ('link_label', models.CharField(default='Subscribe here', max_length=255)),
                ('link_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Hero link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_link_caption',
            field=models.CharField(blank=True, help_text='Text to display on the link button', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A description of the page content', null=True),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('social_platform', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=100)),
                ('link_url', models.CharField(default='', max_length=255)),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_social_links', to='home.FooterSection')),
            ],
            options={
                'verbose_name': 'social link',
                'verbose_name_plural': 'social links',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('link_url', models.URLField(blank=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_section_links', to='home.FooterSection')),
            ],
            options={
                'verbose_name': 'footer link',
                'verbose_name_plural': 'footer links',
            },
        ),
    ]
