# Generated by Django 2.2.2 on 2019-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Sign up for our newsletter to receive regular news and updates', max_length=255)),
                ('link_label', models.CharField(default='Subscribe here', max_length=255)),
                ('link_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Footer Text',
            },
        ),
    ]
