# Generated by Django 2.2.2 on 2019-07-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190709_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
    ]
