# Generated by Django 2.2.2 on 2019-07-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190628_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'Footer Link', 'verbose_name_plural': 'Footer Links'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'verbose_name': 'Footer Section', 'verbose_name_plural': 'Footer Sections'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Social Link', 'verbose_name_plural': 'Social Links'},
        ),
    ]
