# Generated by Django 2.2.2 on 2019-06-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190620_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullink',
            options={'verbose_name': 'useful link', 'verbose_name_plural': 'useful links'},
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
