# Generated by Django 2.2.2 on 2019-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190701_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image_credit_name',
            field=models.CharField(blank=True, help_text='Name of source of image used in hero if any', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_credit_url',
            field=models.URLField(blank=True, help_text='A Link to the original source of the image if any', null=True),
        ),
    ]
