# Generated by Django 2.2.2 on 2019-06-20 13:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0006_auto_20190620_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('link_url', models.URLField(blank=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('related_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'footer link',
                'verbose_name_plural': 'footer links',
            },
        ),
        migrations.DeleteModel(
            name='PageFooterLinks',
        ),
    ]
