# Generated by Django 2.2.2 on 2019-06-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190620_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='footer_links_caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
