# Generated by Django 2.2.3 on 2019-08-12 08:04

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190809_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarpagerelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_pages', to='wagtailcore.Page'),
        ),
    ]
