# Generated by Django 2.2.2 on 2019-06-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190620_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='footer_links_caption',
            new_name='footer_links_title',
        ),
    ]
