# Generated by Django 2.2.2 on 2019-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190621_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlink',
            name='label',
            field=models.CharField(blank=True, help_text='Enter "facebook" or "twitter"', max_length=255),
        ),
        migrations.AlterField(
            model_name='pagefooterlink',
            name='label',
            field=models.CharField(blank=True, help_text='Enter "facebook" or "twitter"', max_length=255),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(blank=True, help_text='Enter "facebook" or "twitter"', max_length=255),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='label',
            field=models.CharField(blank=True, help_text='Enter "facebook" or "twitter"', max_length=255),
        ),
    ]
