# Generated by Django 2.2.2 on 2019-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190621_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(blank=True, help_text='Enter "facebook" or "twitter"', max_length=255),
        ),
    ]
