# Generated by Django 2.2.2 on 2019-06-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190621_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
