# Generated by Django 2.2.2 on 2019-06-24 13:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0016_auto_20190621_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('link_url', models.URLField(blank=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'footer link',
                'verbose_name_plural': 'footer links',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('show_navigation_links', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'footer section',
                'verbose_name_plural': 'footer sections',
            },
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='label',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='page',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='social_platform',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='UsefulLink',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_section_links', to='home.FooterSection'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='section',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_social_links', to='home.FooterSection'),
        ),
    ]
