# Generated by Django 2.2.2 on 2019-06-24 13:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190624_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='section',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_social_links', to='home.FooterSection'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='social_platform',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=100),
        ),
    ]
