# Generated by Django 2.2.2 on 2019-06-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190624_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagefooterlink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagefooterlink',
            name='related_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_links_title',
        ),
        migrations.DeleteModel(
            name='CommunicationLink',
        ),
        migrations.DeleteModel(
            name='PageFooterLink',
        ),
    ]
