# Generated by Django 2.2.3 on 2019-08-27 12:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190826_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertext',
            name='major_content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
