# Generated by Django 2.2.2 on 2019-06-26 08:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0019_auto_20190624_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Hero link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_link_caption',
            field=models.CharField(blank=True, help_text='Text to display on the link button', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A description of the page content', null=True),
        ),
    ]
