# Generated by Django 2.2.3 on 2019-09-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20190919_1544'),
        ('home', '0023_auto_20190906_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image_credit_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image_credit_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_link_caption',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_publication',
            field=models.ForeignKey(blank=True, help_text='The publication to showcase in the page hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='publications.PublicationPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Overwrites the hero image of the featured publication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
