# Generated by Django 2.2.3 on 2019-09-20 09:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0026_auto_20190920_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_work_heading',
            field=models.CharField(blank=True, default='Featured work', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('other_page', models.ForeignKey(blank=True, help_text='A page to link to in the "Other Pages or Related Links" section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_pages', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
