# Generated by Django 2.2.3 on 2019-09-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190920_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_work_heading',
            field=models.CharField(blank=True, default='Featured work', max_length=200, null=True, verbose_name='Section heading'),
        ),
    ]
