# Generated by Django 2.2.3 on 2019-09-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20190920_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_link_caption',
            field=models.CharField(blank=True, default='View full report', help_text='Text to display on the link button', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_publication',
            field=models.ForeignKey(blank=True, help_text='The publication to showcase in the page hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
