# Generated by Django 2.2.3 on 2019-10-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_merge_20191023_0813'),
        ('home', '0035_auto_20191017_0512'),
    ]

    operations = [
    ]
