# Generated by Django 2.2.3 on 2019-10-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20191025_1146'),
        ('home', '0038_auto_20191023_1012'),
    ]

    operations = [
    ]
