# Generated by Django 2.2.6 on 2019-11-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20191126_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_publication',
            field=models.ForeignKey(blank=True, help_text='The page to showcase in the page hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_link_caption',
            field=models.CharField(blank=True, default='View full page', help_text='Text to display on the link button', max_length=255),
        ),
    ]
