# Generated by Django 2.2.8 on 2019-12-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20191128_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagefeaturedwork',
            options={'ordering': ('sort_order',)},
        ),
    ]
