# Generated by Django 3.0.7 on 2020-06-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20200608_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['sort_order'], 'verbose_name': 'Footer Link', 'verbose_name_plural': 'Footer Links'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'ordering': ['sort_order'], 'verbose_name': 'Footer Section', 'verbose_name_plural': 'Footer Sections'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['sort_order'], 'verbose_name': 'Social Link', 'verbose_name_plural': 'Social Links'},
        ),
    ]
