# Generated by Django 2.2.20 on 2021-07-01 17:30

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_auto_20210617_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('body', wagtail.core.fields.RichTextField()),
            ],
        ),
    ]
