# Generated by Django 2.2.20 on 2021-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_cookienotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookienotice',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cookienotice',
            name='heading',
            field=models.CharField(default='Notice', max_length=255),
        ),
    ]
