# Generated by Django 2.2.20 on 2021-07-02 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_cookie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cookie',
            new_name='CookieNotice',
        ),
    ]
