# Generated by Django 2.2.20 on 2021-07-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20210702_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookienotice',
            old_name='text',
            new_name='heading',
        ),
    ]
