# Generated by Django 2.2.16 on 2021-07-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20210702_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookienotice',
            name='title',
        ),
        migrations.AddField(
            model_name='cookienotice',
            name='download_link_caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Caption'),
        ),
        migrations.AlterField(
            model_name='cookienotice',
            name='cookie_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Policy Doc'),
        ),
        migrations.AlterField(
            model_name='cookienotice',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
