# Generated by Django 2.2.20 on 2021-07-02 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0071_auto_20210702_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookienotice',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
