# Generated by Django 2.2.20 on 2021-07-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_auto_20210705_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookienotice',
            options={'verbose_name': 'Cookie Notice', 'verbose_name_plural': 'Cookie Notices'},
        ),
    ]
