# Generated by Django 2.2.20 on 2021-07-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_cookienotice_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookienotice',
            old_name='policy',
            new_name='cookie_policy',
        ),
    ]
