# Generated by Django 2.2.20 on 2021-07-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_auto_20210702_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookienotice',
            name='link_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
