# Generated by Django 2.2.20 on 2021-07-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_auto_20210702_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookienotice',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
