# Generated by Django 2.2.20 on 2021-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_auto_20210702_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookienotice',
            name='body',
            field=models.TextField(),
        ),
    ]
