# Generated by Django 3.2.24 on 2024-02-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_auto_20231117_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CookieNotice',
        ),
    ]
