# Generated by Django 3.2.25 on 2024-07-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0078_auto_20231117_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookienotice',
            name='cookie_policy',
        ),
        migrations.RemoveField(
            model_name='cookienotice',
            name='download_link_caption',
        ),
        migrations.AddField(
            model_name='cookienotice',
            name='set_cookie_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page'),
        ),
    ]
