# Generated by Django 2.2.3 on 2019-07-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventindexpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventindexpage',
            options={'verbose_name': 'Event Index Page'},
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'verbose_name': 'Event Page'},
        ),
        migrations.AddField(
            model_name='eventpage',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
