# Generated by Django 2.2.3 on 2019-07-31 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190731_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
