# Generated by Django 2.2.3 on 2019-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190902_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
