# Generated by Django 2.2.2 on 2019-10-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20191011_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='raw_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
