# Generated by Django 2.2.2 on 2019-10-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20191017_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='hero_image_credit_name',
            field=models.TextField(blank=True, help_text='Name of source of image used in hero if any', null=True, verbose_name='Image credit name'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='hero_image_credit_name',
            field=models.TextField(blank=True, help_text='Name of source of image used in hero if any', null=True, verbose_name='Image credit name'),
        ),
    ]
