# Generated by Django 3.0.7 on 2020-06-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20191125_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpagerelatedlink',
            options={'ordering': ['sort_order']},
        ),
    ]
