# Generated by Django 3.1 on 2020-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_eventpage_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='timezone',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='time_and_location',
            field=models.TextField(blank=True, help_text='Time and location information for event', max_length=160, null=True),
        ),
    ]
