# Generated by Django 3.1 on 2020-11-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20201103_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='time',
            field=models.CharField(blank=True, help_text='Time information for event', max_length=160, null=True),
        ),
    ]
