# Generated by Django 2.2.2 on 2019-07-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190711_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
