# Generated by Django 2.2.2 on 2019-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=False, help_text="Should this user's profile be displayed as staff?"),
        ),
    ]
