# Generated by Django 2.2.2 on 2019-06-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190627_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('LEA', 'Leadership Team'), ('DAT', 'Data Science & Information Architecture'), ('REA', 'Research & Analysis'), ('PRO', 'Project Management'), ('HRF', 'HR, Facilities, IT & Finance'), ('STR', 'Strategic Partnerships'), ('COM', 'Communications'), ('POL', 'Policy & Engagement'), ('NON', 'Non-Executive Directors'), ('BOA', 'Board Members'), ('CON', 'Consultants'), ('FEL', 'Fellow')], max_length=3, null=True),
        ),
    ]
