# Generated by Django 2.2.4 on 2019-11-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190808_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
