# Generated by Django 2.2.3 on 2019-08-21 10:23

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0002_auto_20190821_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedopage',
            name='our_locations_description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='whatwedopage',
            name='our_locations_heading',
            field=models.CharField(blank=True, default='Where We Work', max_length=250, verbose_name='Heading'),
        ),
    ]
