# Generated by Django 2.2.3 on 2019-08-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0003_auto_20190821_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatwedopage',
            old_name='our_locations_description',
            new_name='places_description',
        ),
        migrations.RenameField(
            model_name='whatwedopage',
            old_name='our_locations_heading',
            new_name='places_heading',
        ),
    ]
