# Generated by Django 2.2.3 on 2019-08-21 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20190819_1017'),
        ('whatwedo', '0004_auto_20190821_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedopage',
            name='places_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='place.PlacesPage'),
        ),
    ]
