# Generated by Django 2.2.3 on 2019-08-22 12:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0005_whatwedopage_places_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedopage',
            name='sections',
            field=wagtail.core.fields.StreamField([('locations_map', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(icon='fa-heading', required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'document', 'image', 'embed'], icon='fa-paragraph', required=False, template='blocks/paragraph_block.html')), ('button', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False))])), ('light', wagtail.core.blocks.BooleanBlock(default=False, help_text='Applies a lighter background to the section'))]))], blank=True, null=True, verbose_name='Page Body'),
        ),
    ]
