# Generated by Django 2.2.3 on 2019-08-22 12:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0006_whatwedopage_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatwedopage',
            name='places_description',
        ),
        migrations.RemoveField(
            model_name='whatwedopage',
            name='places_heading',
        ),
        migrations.RemoveField(
            model_name='whatwedopage',
            name='places_page',
        ),
        migrations.AlterField(
            model_name='whatwedopage',
            name='sections',
            field=wagtail.fields.StreamField([('locations_map', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(icon='fa-heading', required=False)), ('description', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'document', 'image', 'embed'], icon='fa-paragraph', required=False, template='blocks/paragraph_block.html')), ('button', wagtail.blocks.StructBlock([('caption', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.URLBlock(required=False)), ('page', wagtail.blocks.PageChooserBlock(required=False))])), ('light', wagtail.blocks.BooleanBlock(default=False, help_text='Applies a lighter background to the section', required=False))]))], blank=True, null=True, verbose_name='Sections'),
        ),
    ]
