# Generated by Django 2.2.3 on 2019-08-23 11:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0007_auto_20190822_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedopage',
            name='sections',
            field=wagtail.core.fields.StreamField([('locations_map', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(icon='fa-heading', required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'document', 'image', 'embed'], icon='fa-paragraph', required=False, template='blocks/paragraph_block.html')), ('button', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False))])), ('light', wagtail.core.blocks.BooleanBlock(default=False, help_text='Applies a lighter background to the section', required=False))])), ('focus_area', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Our focus areas', icon='fa-heading', required=False)), ('focus_areas', wagtail.core.blocks.ListBlock(wagtail.core.blocks.TextBlock(icon='fa-text'), required=False)), ('button', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False))])), ('light', wagtail.core.blocks.BooleanBlock(default=False, help_text='Applies a lighter background to the section', required=False))])), ('expertise', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(default='Our expertise', icon='fa-heading', required=False)), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'document', 'image', 'embed'], icon='fa-paragraph', required=False, template='blocks/paragraph_block.html')), ('expertise_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(icon='fa-text')), ('description', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'document', 'image', 'embed'], icon='fa-paragraph', required=False, template='blocks/paragraph_block.html'))]), required=False)), ('light', wagtail.core.blocks.BooleanBlock(default=False, help_text='Applies a lighter background to the section', required=False))]))], blank=True, null=True, verbose_name='Sections'),
        ),
    ]
