# Generated by Django 2.2.3 on 2019-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0012_auto_20190826_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedopage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='More about', max_length=255, verbose_name='Heading'),
        ),
    ]
