# Generated by Django 2.2.3 on 2019-10-10 15:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0023_servicespage_richtext_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='richtext_columns',
            field=wagtail.core.fields.StreamField([('column', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(icon='title', required=False)), ('content', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'anchor'], icon='fa-paragraph'))], template='blocks/richtext_column.html'))], blank=True, null=True),
        ),
    ]
