# Generated by Django 2.2.3 on 2019-10-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0027_auto_20191017_0512'),
        ('whatwedo', '0028_merge_20191023_0813'),
    ]

    operations = [
    ]
