# Generated by Django 2.2.4 on 2019-11-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0036_whereweworklocations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhereWeWorkLocations',
        ),
    ]
