# Generated by Django 2.2.4 on 2019-11-06 08:54

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0038_locationswherewework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationswherewework',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_where_we_work', to='wagtailcore.Page'),
        ),
    ]
