# Generated by Django 2.2.4 on 2019-11-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('whatwedo', '0039_auto_20191106_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationswherewework',
            options={},
        ),
        migrations.AddField(
            model_name='locationswherewework',
            name='other_page',
            field=models.ForeignKey(blank=True, help_text='A page to link to in the "Other Pages or Related Links" section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Page'),
        ),
    ]
