# Generated by Django 2.2.4 on 2019-11-06 10:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailgeowidget.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0040_auto_20191106_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedopage',
            name='locations_where_we_work',
            field=wagtail.core.fields.StreamField([('location', wagtail.core.blocks.TextBlock()), ('address', wagtail.core.blocks.TextBlock()), ('map', wagtailgeowidget.blocks.GeoBlock())], default=''),
        ),
        migrations.DeleteModel(
            name='LocationsWhereWeWork',
        ),
    ]
