# Generated by Django 2.2.4 on 2019-11-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0037_auto_20191107_1356'),
        ('whatwedo', '0045_auto_20191109_1925'),
    ]

    operations = [
    ]
