# Generated by Django 2.2.2 on 2019-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarymenulinks',
            name='hidden',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
