# Generated by Django 2.2.2 on 2019-07-18 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('common', '0002_download'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('vacancies', '0002_auto_20190717_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacanciesPage',
            new_name='VacancyIndexPage',
        ),
    ]
