# Generated by Django 2.2.2 on 2019-07-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20190718_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyindexpage',
            options={'verbose_name': 'Vacancy Index Page'},
        ),
        migrations.RemoveField(
            model_name='vacancyindexpage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='vacancypage',
            name='hero_title',
        ),
    ]
