# Generated by Django 2.2.3 on 2019-07-31 13:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('vacancies', '0006_auto_20190729_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyRelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('other_page', models.ForeignKey(blank=True, help_text='Choose a page to link to in the "Other Pages" section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Other Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_pages', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
