# Generated by Django 2.2.3 on 2019-07-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancyrelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyrelatedlink',
            name='other_page',
            field=models.ForeignKey(blank=True, help_text='A page to link to in the "Other Pages or Related Links" section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Page'),
        ),
    ]
