# Generated by Django 2.2.3 on 2019-08-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_auto_20190809_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='Learn more about Developement Initiatives', max_length=255, verbose_name='Heading'),
        ),
        migrations.DeleteModel(
            name='VacancyRelatedLink',
        ),
    ]
