# Generated by Django 2.2.3 on 2019-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_auto_20190819_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='address',
            field=models.TextField(blank=True, help_text="E.g. 'North Quay House Quay Side, Temple Back Bristol, BS1 6FL, UK'"),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='contact',
            field=models.CharField(blank=True, help_text="E.g. '+44 (0) 1179 272 505'", max_length=255),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
