# Generated by Django 2.2.3 on 2019-09-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0023_auto_20190920_1040'),
        ('vacancies', '0023_vacancydownload'),
    ]

    operations = [
    ]
