# Generated by Django 2.2.3 on 2019-10-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0028_auto_20191023_0700'),
        ('vacancies', '0028_auto_20191023_0650'),
    ]

    operations = [
    ]
