# Generated by Django 2.2.2 on 2019-10-24 06:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0029_merge_20191023_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officelocation',
            name='address',
            field=wagtail.core.fields.RichTextField(blank=True, help_text="E.g. 'North Quay House Quay Side, Temple Back Bristol, BS1 6FL, UK'", null=True),
        ),
    ]
