# Generated by Django 2.2.3 on 2019-10-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0030_auto_20191024_0646'),
        ('vacancies', '0031_auto_20191023_1012'),
    ]

    operations = [
    ]
