# Generated by Django 2.2.3 on 2019-10-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0032_merge_20191025_0957'),
        ('vacancies', '0031_auto_20191025_1146'),
    ]

    operations = [
    ]
