# Generated by Django 2.2.4 on 2019-11-04 13:17

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0035_auto_20191030_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyindexpage',
            name='email_alert_confirmation',
            field=models.BooleanField(default=False, verbose_name='Opt In to Email Alerts'),
        ),
        migrations.AddField(
            model_name='vacancyindexpage',
            name='email_alert_confirmation_label',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Consent to data capture for email alerts.', verbose_name='Descriptive Text for Consent to Email Alerts'),
        ),
    ]
