# Generated by Django 2.2.4 on 2019-11-04 13:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0036_auto_20191104_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyindexpage',
            name='email_alert_confirmation',
        ),
        migrations.AlterField(
            model_name='vacancyindexpage',
            name='email_alert_confirmation_label',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Descriptive Text for Consent to Email Alerts'),
        ),
    ]
