# Generated by Django 2.2.4 on 2019-11-04 15:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0038_auto_20191104_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyindexpage',
            name='email_alert_confirmation_label',
            field=wagtail.core.fields.RichTextField(blank=True, default='By checking this box you consent to us collecting the data submitted', verbose_name='Descriptive Text for Consent to Email Alerts'),
        ),
    ]
