# Generated by Django 2.2.4 on 2019-11-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0039_auto_20191107_1356'),
        ('vacancies', '0039_auto_20191104_1507'),
    ]

    operations = [
    ]
