# Generated by Django 2.2.4 on 2019-12-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0047_vacancypage_second_interview_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancypage',
            old_name='second_interview_date',
            new_name='second_interview',
        ),
    ]
