# Generated by Django 2.2.4 on 2019-12-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0048_auto_20191203_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancypage',
            old_name='application_close_date',
            new_name='application_close',
        ),
        migrations.RenameField(
            model_name='vacancypage',
            old_name='first_interview_date',
            new_name='first_interview',
        ),
        migrations.RenameField(
            model_name='vacancypage',
            old_name='job_start_date',
            new_name='job_start',
        ),
    ]
