# Generated by Django 2.2.12 on 2020-05-16 22:02

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0049_auto_20191203_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypage',
            name='first_interview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
