# Generated by Django 2.2.12 on 2020-05-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0049_auto_20191203_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypage',
            name='first_interview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancypage',
            name='second_interview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
