# Generated by Django 2.2.6 on 2020-04-26 13:17
import re
from django.db import migrations
from datetime import datetime


def convert_to_date(apps, schema_editor):
    VacancyPage = apps.get_model('vacancies', 'VacancyPage')
    for vacancy in VacancyPage.objects.all():
        if vacancy.first_interview:
            try:
                match = re.search(r'\d{4}-\d{2}-\d{2}', vacancy.first_interview)
                if match:
                    vacancy.first_interview = datetime.strptime(match.group(1), '%d%m%Y').date()
                else:
                    vacancy.first_interview = None
            except:
                vacancy.first_interview = None
            vacancy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0050_auto_20200516_2202'),

    ]

    operations = [
        migrations.RunPython(convert_to_date),
    ]
