# Generated by Django 2.2.12 on 2020-05-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0057_auto_20200514_0956'),
        ('vacancies', '0050_auto_20200518_0831'),
    ]

    operations = [
    ]
