# Generated by Django 3.0.7 on 2020-06-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0058_auto_20200518_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypage',
            name='other_pages_heading',
            field=models.CharField(blank=True, default='Learn more about Development Initiatives', max_length=255, verbose_name='Heading'),
        ),
    ]
