# Generated by Django 3.2.12 on 2022-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0064_auto_20210617_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_close', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'applications close',
            },
        ),
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_scale', models.CharField(blank=True, max_length=225)),
            ],
            options={
                'verbose_name': 'salary scale',
                'verbose_name_plural': 'salary scales',
            },
        ),
    ]
