# Generated by Django 3.2.12 on 2022-02-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0066_auto_20220205_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancypage',
            name='salary_scale',
        ),
        migrations.AddField(
            model_name='vacancypage',
            name='salary_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.salaryscale'),
        ),
    ]
