# Generated by Django 3.2.12 on 2022-02-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0067_auto_20220205_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryscale',
            name='title',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
