# Generated by Django 3.2.12 on 2022-02-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0070_auto_20220205_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypage',
            name='application_close',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.closingdate'),
        ),
    ]
