# Generated by Django 3.2.12 on 2022-02-05 20:48

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0071_alter_vacancypage_application_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancypage',
            name='application_close',
        ),
        migrations.AddField(
            model_name='vacancypage',
            name='application_close',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='vacancies.ClosingDate'),
        ),
    ]
